### ISSUE TITLE
Remove byteorder-dependency

### ISSUE THREAD

**Issue by lukaslueg** [image-rs/image#1000]
The `byteorder`-dependency is not strictly needed since 1.32. Removing it would cut down the dependencies, raising the minimum Rust version on the other hand.

Is there interest in removing it?

**Comment by HeroicKatora** [comment]
Technically it would be useful to have fewer dependencies, especially if they have been somewhat absorbed into the standard library. It would be necessary to start with the dependencies though, `jpeg-decoder` and `tiff` also use `byteorder` and since they are compatible versions the usage here should not lead to duplicate compilation.

**Comment by fintelia** [comment]
I'd be hesitant to remove it right at the moment. The crate is slightly haphazard about endianness considerations right now, and resolving that might involve adding the dependency back.
