### ISSUE TITLE
Support EXIF 

### ISSUE THREAD

**Issue by schulzch** [image-rs/image#1045]
I would like to be able to read and write [EXIF](https://en.wikipedia.org/wiki/Exif) meta data, especially for PNG and JPEG.

My specific use case for this functionality is 
a) storing/loading configuration within/from screenshots for reproducibility,
b) maintaining metadata when processing images.

If there is interest I would be very willing to implement this - hints and feedback welcome :)

**Comment by fintelia** [comment]
:+1:  I think the way to do this would be to implement this first for a single format, directly on the encoder/decoder and then if we can find a clean/general API extend it to more formats.

**Comment by HeroicKatora** [comment]
Seems like a problem similar to `Limits` for decoder but for the encoders.

**Comment by kaj** [comment]
There is a few packages providing exif info currently.  I use [kamadak-exif](https://lib.rs/crates/kamadak-exif) in a project and is quite happy with that. But yes, better integration with the image echosystem would probably be nice.

**Comment by birktj** [comment]
You may be interested in https://github.com/image-rs/image-png/issues/116

**Comment by maghoff** [comment]
This is also neccessary for [correctly orienting JPEGs](https://magnushoff.com/articles/jpeg-orientation/).

It could be argued that orientation correction should be automatically applied to the pixel buffer, making it even more important to integrate this functionality rather than pointing to other crates :slightly_smiling_face:

**Comment by lovasoa** [comment]
I recently got a feature request that would require image-rs to support writing EXIF data:
https://github.com/lovasoa/dezoomify-rs/issues/12

So, 👍 on this !

**Comment by zeh** [comment]
One year later (!) but this would be great.

I'm saving images using image and would like to add some basic metadata to them, but there's no good way to do it!

Strangely, currently, there's _no_ good create for _writing_ EXIF data for Rust. There's a bunch of crates to _read_ metadata, and a few wrappers for some C libraries (ugh), but a pure Rust EXIF writer ins nowhere to be found.

I could see this being a separate crate just for EXIF writing (depending on format) and then exposed somehow so Image can make use of it when writing images to disk.

**Comment by paolobarbolini** [comment]
> currently there's no good create for writing EXIF data for Rust

You should be able to do so with the help of [kamadak-exif](https://crates.io/crates/kamadak-exif) to encode the EXIF data and [img-parts](https://crates.io/crates/img-parts) (I'm the author of it) to write it to an existing image.

See also https://github.com/kamadak/exif-rs/issues/1

**Comment by zeh** [comment]
> > currently there's no good create for writing EXIF data for Rust
> 
> You should be able to do so with the help of [kamadak-exif](https://crates.io/crates/kamadak-exif) to encode the EXIF data and [img-parts](https://crates.io/crates/img-parts) (I'm the author of it) to write it to an existing image.

Thanks for the tip. I hadn't ran into img-parts before when trying to find libraries for my use case. I managed to [add metadata writing to a project of mine](https://github.com/zeh/random-art-generator/blob/dev/src/main.rs#L162-L220) using img-parts and it seems to be working well. A bit suboptimal since it writes the file, reads it, and writes it again with metadata, but it's "good enough" for now.

---

After implementing this feature and doing some research on the problem space I think it might actually _not_ be a good idea for `image` to try and provide a way to write EXIF or other metadata. The feature is more complicated than I thought; it would make total sense to have this as a dedicated, separate library.

In fact, I wonder if it makes sense for `image` to implement `save()` at all, given the edge cases required for it to properly work (say, JPEG rotation as mentioned). It's convenient, for sure, but not always enough; it can probably work for 98% of the use cases out there, but the rest 2% end up requiring a radically different solution. For my specific use case, since I require metadata too, to avoid having to write the file twice it would be better to have a `to_file_buffer()` that saves the encoded image to a buffer (basically exposing `save_buffer_impl()`) so it can be used elsewhere - adding metadata, etc - before writing the file.

(Note: I'm not an advanced Rust programmer, so I might be missing a better solution for my use case.)

**Comment by paolobarbolini** [comment]
> For my specific use case, since I require metadata too, to avoid having to write the file twice it would be better to have a to_file_buffer() that saves the encoded image to a buffer

The `image` crate already supports it. Instead of using  `save()`, which takes the path to where you want the file to be saved to, you can use [`write_to()`, which asks for a `Write`r](https://docs.rs/image/0.23.12/image/enum.DynamicImage.html#method.write_to ). With it you can make it write into a buffer, just as I show in [this example](https://github.com/paolobarbolini/img-parts/blob/fa23682517eed028ce0061e670d93fe6c5aaf9eb/examples/image-rs/src/main.rs#L69-L73).

**Comment by zeh** [comment]
> The `image` crate already supports it. Instead of using `save()`, which takes the path to where you want the file to be saved to, you can use [`write_to()`, which asks for a `Write`r instead](https://docs.rs/image/0.23.12/image/enum.DynamicImage.html#method.write_to). With it you can make it write into a buffer, just as I show in [this example](https://github.com/paolobarbolini/img-parts/blob/fa23682517eed028ce0061e670d93fe6c5aaf9eb/examples/image-rs/src/main.rs#L69-L73).

Ah, I see. I was using `ImageBuffer`, which didn't expose `write_to()`, unlike `DynamicImage`. Still a but confused about those abstractions. I'll use that instead.

**Comment by stephanbogner** [comment]
I'd also appreciate this (mainly to preserve image rotation).

**My workaround:**
I [found an example](https://github.com/paolobarbolini/img-parts/blob/fa23682517eed028ce0061e670d93fe6c5aaf9eb/examples/image-rs/src/main.rs) on how to integrate `img-parts` with `image` ... but I couldn't get it to work.

What I now did instead: I use [kamadak-exif](https://lib.rs/crates/kamadak-exif) (which I already use anyway to get the exif date information) and rotate/flip the image myself using [`image::imageops`](https://docs.rs/image/latest/image/imageops/index.html) ([with information from here](https://magnushoff.com/articles/jpeg-orientation/) on what the exif rotation values mean).
Not an ideal solution, but it works and I only load and save the image once.

**Comment by marcalj** [comment]
> I'd also appreciate this (mainly to preserve image orientation/rotation).
> 
> **My workaround:** I [found an example](https://github.com/paolobarbolini/img-parts/blob/fa23682517eed028ce0061e670d93fe6c5aaf9eb/examples/image-rs/src/main.rs) on how to integrate `img-parts` with `image` ... but I couldn't get it to work.
> 
> What I now did instead: I use [`kamadak-exif`](https://lib.rs/crates/kamadak-exif) (which I already use anyway to get the exif date information) and rotate/flip the image myself using [`image::imageops`](https://docs.rs/image/latest/image/imageops/index.html) ([with information from here](https://magnushoff.com/articles/jpeg-orientation/) on what the exif orientation values mean). Not an ideal solution, but it works and I only load and save the image once.

I'm using your approach and I'm wondering how to read the EXIF data without having to clone the image buffer. Since loading the buffer as an image moves the value. Any thoughts? Thanks.

**Comment by marcalj** [comment]
Ok, since my input is a buffer, I can read EXIF data without modifying the buffer like this:

```rs
// input: image_buffer: &[u8]
let exif_reader = exif::Reader::new();
let exif = exif_reader.read_raw(image_buffer.to_vec());
```

**Comment by marvinruder** [comment]
> > I'd also appreciate this (mainly to preserve image orientation/rotation).
> > **My workaround:** I [found an example](https://github.com/paolobarbolini/img-parts/blob/fa23682517eed028ce0061e670d93fe6c5aaf9eb/examples/image-rs/src/main.rs) on how to integrate `img-parts` with `image` ... but I couldn't get it to work.
> > What I now did instead: I use [`kamadak-exif`](https://lib.rs/crates/kamadak-exif) (which I already use anyway to get the exif date information) and rotate/flip the image myself using [`image::imageops`](https://docs.rs/image/latest/image/imageops/index.html) ([with information from here](https://magnushoff.com/articles/jpeg-orientation/) on what the exif orientation values mean). Not an ideal solution, but it works and I only load and save the image once.
> 
> I'm using your approach and I'm wondering how to read the EXIF data without having to clone the image buffer. Since loading the buffer as an image moves the value. Any thoughts? Thanks.

I am doing something similar with

```rust
// input: image_buffer: &[u8]
exif::Reader::new().read_from_container(&mut std::io::Cursor::new(image_buffer))
```

**Comment by marcalj** [comment]
> ```rust
> // input: image_buffer: &[u8]
> exif::Reader::new().read_from_container(&mut std::io::Cursor::new(image_buffer))
> ```

AFAIK is also creating a copy of the buffer.

**Comment by Shnatsel** [comment]
Reading Exif chunks was implemented for JPEG and WebP in https://github.com/image-rs/image/pull/2291 and https://github.com/image-rs/image/pull/2319

No writing support yet

**Comment by mschnell1** [comment]
> > You should be able to do so with the help of [kamadak-exif](https://crates.io/crates/kamadak-exif) to encode the EXIF data and [img-parts](https://crates.io/crates/img-parts) (I'm the author of it) to write it to an existing image.

Writing a ImageDescription into an existing JPG file.

I already tested this with kamadak-exif, but when just doing so the file seems to feature no image any more :( 
trying to use `set_jpeg()`failed, as I don't seem to be able to extract the jpeg picture data.

**Comment by mschnell1** [comment]
Here -> https://github.com/image-rs/image/issues/1045 you write it already should work ????

**Comment by marcalj** [comment]
Coming back to this issue, I found this approach already included now. Not sure if before July it was also available. I was able to remove usage of `kamadak-exif` and rotation & flip calls. Thank you guys!

https://docs.rs/image/0.25.5/image/enum.DynamicImage.html#method.apply_orientation

```rs
use image::{DynamicImage, ImageReader, ImageDecoder};

let mut decoder = ImageReader::open("file.jpg")?.into_decoder()?;
let orientation = decoder.orientation()?;
let mut image = DynamicImage::from_decoder(decoder)?;
image.apply_orientation(orientation);
```

**Comment by fintelia** [comment]
Yeah, we added support for reading orientation and data EXIF quite recently. I'm going to go ahead and close this issue since initial support has landed, but feel free to open new issues for specific missing functionality. 

PS: If you want to see when a given feature was added, you can check the CHANGES.md file
