### ISSUE TITLE
GenericImageView::bounds should return (i32, i32, u32, u32)

### ISSUE THREAD

**Issue by flappyBug** [image-rs/image#1079]
Currently `GenericImageView::bounds` returns `(u32, u32, u32, u32)`, which stands for `(xoffset, yoffset, xstride, ystride)`. It's adequate for `SubImage` use case. but xoffset and yoffset could be negative in some other cases, and how the pixels out of original image bound can be filled depends on [boundary pad options](https://www.mathworks.com/help/images/imfilter-boundary-padding-options.html).

**Comment by HeroicKatora** [comment]
With `(i32, i32, u32, u32)` you can not represent all possible configurations as well. It does not appear to be a better type in this regard. 

You note that the current types make overlay operations *unergonomic* but it should be said that the interface is nonetheless *sufficient*. For example instead of negative relative coordinates `(-1, -1)`, select the subimage `(1, 1, width - 1, height - 1)`  of the source and place it at `(0, 0)` onto the target.

For alternative boundary behaviour I'll have to refer You to [`imageproc`](https://github.com/image-rs/imageproc/issues/2) where more generic transformation code is available (I'm sure they'd appreciate a PR closing this outstanding issue).

**Comment by flappyBug** [comment]
Thanks for your reply. I was exactly raising this issue when investigating `imageproc` filters. After days, I realize that image views out of boundary are not necessary to implement `GenericImageView` but just mimic some methods that `GenericImageView` provides. Changing the signature of `GenericImageView::bounds` will lead a lot of breaking changes, so I think it's fine to close this issue.
