### ISSUE TITLE
Implement Bayer filter-based colour spaces

### ISSUE THREAD

**Issue by nagisa** [image-rs/image#1084]
Mostly creating this issue to evaluate interest and sensibility in doing this. Cameras generally will produce image frames with pixels in [Bayer* colourspaces](https://en.wikipedia.org/wiki/Bayer_filter), so it is a fairly important colour space to handle.

I think it would be cool to have support for this colourspace in `image`, but there are a couple of API-related complications, that make this a non-trivial and non-obvious addition:

* A single Bayer* pixel does not uniquely describe the colour, instead interpolation of some sort ([demosaicing](https://en.wikipedia.org/wiki/Demosaicing)) must be used. As thus, `Bayer*` pixels cannot implement `Pixel::to_rgb` and similar methods, for instance;
* Many of the Container traits like `GenericImage` or `GenericImageView` cannot be implemented right now as-is either, because `Bayer*` cannot implement `Pixel`;
* Some of the `imageops` and `colorops` do not make sense as-is on `Bayer*` images…
* Probably many more.

**Comment by HeroicKatora** [comment]
It would be possible to implement a container decoding/encoding these without immediately making them available as a `GenericImage`. But the most complicated assumption is that pixels are contiguous in memory, moving the color space functions from the `Pixel` trait¹ would not fix this.

¹ I want to move `Pixel::to_rgb` and other color space related functions to some higher-level trait at some point in any case, since it doesn't do a good job of implementing correct color treatment for the *existing* types.

**Comment by nagisa** [comment]
My use-case for this would be dealing with image data buffers that I already have in memory, so simple decoding mechanism is insufficient.

**Comment by Shnatsel** [comment]
What kind of operations do you need to perform on images in Bayer* colorspace? AFAIK Bayer* images are not meant to be edited directly - rather, converted into RGB and edited from there.

**Comment by nagisa** [comment]
We currently just save/load the image data and demosaic (convert the colourspace) to something else.

I think you’re right that there's not much benefit in supporting transformations or other non-conversion operations on Bayer* images, but IMO it would be a shame if the API for loading/converting Bayer* images was significantly different from the API for, say, RGB PNG.
