### ISSUE TITLE
Why doesn't DynamicImage::write_to return io::Result?

### ISSUE THREAD

**Issue by GarkGarcia** [image-rs/image#1098]
Browsing through the source code of [`DynamicImage::write_to`](https://docs.rs/image/0.22.3/image/enum.DynamicImage.html#method.write_to), it doesn't seem to be a clear reason for the choice of `ImageResult`.

Apparently, the only reason why it returns an `ImageResult` instead of an `io::Result` is that `image::gif::Encoder::encode` does the same. However, browsing through `image::gif::Encoder::encode`, one can clearly see it does not return any `ImageResult` variant other than `IoError`. 

Is there a particular reason why `DynamicImage::write_to` returns an `ImageResult` instead of an `io::Result`? If not, the method's signature should be reconsidered.

**Comment by HeroicKatora** [comment]
Not all formats support all possible dimensions and trying to encode a too large image for example should produce an error rather than a corrupted image (see #1097 for one example that's currently being fixed).

There's a lot of variety of formats and many different possible data errors where wrapping into an `std::io::Error` loses expressiveness, the power of matching and makes the implementation more verbose. In fact, the next release will probably switch even more encoders to `ImageResult` since many internal errors are currentl wrapped in an `io::Error` instead of being returned directly.
