### ISSUE TITLE
Contract for and details of ImageDecoderExt confusing

### ISSUE THREAD

**Issue by nabijaczleweli** [image-rs/image#1174]
This happens in 0.23.2, as seen on docs.rs.

## Expected

Relatively important questions that popped into my head as I was (trying to) implement this to be answered:
  * When is "periodically"?
  * Is the output buffer always to size?
  * Who calls this?
  * What's the output format?

## Actual behaviour

Having the benefit of implementing this from inside `image` I could use `load_image()` that all existing implementations use to gleam some sort of data out of this:
  * "Periodically" seems to be once at the start, then after each chunk (can users depend on this?).
  * I'm still not sure, because
  * Nobody in `image` actually calls `read_rect{,_with_progress}()`
    ```
    Searching 2379 files for "read_rect"

    T:\image\src\bmp\decoder.rs:
     1417  
     1418  impl<'a, R: 'a + Read + Seek> ImageDecoderExt<'a> for BmpDecoder<R> {
     1419:     fn read_rect_with_progress<F: Fn(Progress)>(
     1420          &mut self,
     1421          x: u32,

    T:\image\src\dxt.rs:
      148  
      149  impl<'a, R: 'a + Read + Seek> ImageDecoderExt<'a> for DxtDecoder<R> {
      150:     fn read_rect_with_progress<F: Fn(Progress)>(
      151          &mut self,
      152          x: u32,

    T:\image\src\farbfeld.rs:
      145  
      146  impl<'a, R: 'a + Read + Seek> ImageDecoderExt<'a> for FarbfeldDecoder<R> {
      147:     fn read_rect_with_progress<F: Fn(Progress)>(
      148          &mut self,
      149          x: u32,
      ...
      234  
      235      #[test]
      236:     fn read_rect() {
      237          static RECTANGLE_IN: &[u8] =  b"farbfeld\
      238                                          \x00\x00\x00\x02\x00\x00\x00\x03\
      ...
      248          FarbfeldDecoder::new(Cursor::new(RECTANGLE_IN))
      249              .unwrap()
      250:             .read_rect_with_progress(1, 1, 1, 2, &mut out_buf, |p| println!("{:?}", p))
      251              .unwrap();
      252          assert_eq!(out_buf, RECTANGLE_OUT);

    T:\image\src\hdr\decoder.rs:
      100  
      101  impl<'a, R: 'a + BufRead + Seek> ImageDecoderExt<'a> for HDRAdapter<R> {
      102:     fn read_rect_with_progress<F: Fn(Progress)>(
      103          &mut self,
      104          x: u32,

    T:\image\src\image.rs:
      435  pub trait ImageDecoderExt<'a>: ImageDecoder<'a> + Sized {
      436      /// Read a rectangular section of the image.
      437:     fn read_rect(
      438          &mut self,
      439          x: u32,
      ...
      443          buf: &mut [u8],
      444      ) -> ImageResult<()> {
      445:         self.read_rect_with_progress(x, y, width, height, buf, |_|{})
      446      }
      447  
      448      /// Read a rectangular section of the image, periodically reporting progress.
      449:     fn read_rect_with_progress<F: Fn(Progress)>(
      450          &mut self,
      451          x: u32,

    T:\image\target\debug\deps\libimage-a241cf79f5d7c0ae.rlib:
        <binary>

    T:\image\target\debug\deps\libimage-a241cf79f5d7c0ae.rmeta:
        <binary>

    T:\image\target\debug\deps\libimage-d0da2ba8df5bc364.rlib:
        <binary>

    T:\image\target\debug\deps\libimage-d0da2ba8df5bc364.rmeta:
        <binary>

    T:\image\target\debug\incremental\image-2r0fteddb5a4j\s-flxixajpnf-ywiml6-s3qh4mp5t9wc\query-cache.bin:
        <binary>

    T:\image\target\debug\libimage.rlib:
        <binary>

    47 matches across 11 files
    ```
    which is worrying in its own right.
  * I'm assuming it's native-endian in `color_type()`-field-order, but I have the benefit of being able to copy `load_rect()` calls, so.

## Reproduction steps

1. Open https://docs.rs/image/0.23.2/image/trait.ImageDecoderExt.html
2. Implement the trait to the spec

**Comment by fintelia** [comment]
Thanks for posting this issue, it really helps me see how the documentation is confusing! I'm going to answer each of your questions below so we are hopefully on the same page about what the trait does, and then we figure out how to make the documentation clearer.

> Who calls this?

This trait is meant to be used by end-users of the image library. Anyone who has an image file they want to decode can create a suitable decoder for it (probably by using something like _XxxDecoder::new(File::open("img.xxx")?)_).

Any decoder that implements _ImageDecoderExt_ must also implement _ImageDecoder_, so using _read_image()_ is always an option instead of _read_rect()_. The second option is preferable if only part of the image needs to be loaded since it avoids wasting memory/decoding time for the rest.

> When is "periodically"?

Hard to give an exact answer, but ideally frequently enough to display a loading bar for the user.

> Is the output buffer always to size?

Yes. The function should panic otherwise. 

> What's the output format?

Whatever is returned by _ImageDecoder::color_type()_, with all pixel data packed and in native endian order.

**Comment by nabijaczleweli** [comment]
Thanks for the explanation! I've opened #1177 with proposed wording.
