### ISSUE TITLE
Support for Looping GIF's

### ISSUE THREAD

**Issue by SystematicLoop** [image-rs/image#1175]
Correct me if I am wrong, but I cannot locate a way to specify that a GIF should loop when encoding the frames. All I can do for a frame is specify the delay.

**Comment by sotrh** [comment]
I'm also having this issue.
```rust
fn save_gif(path: &str, frames: &mut Vec<Vec<u8>>, speed: i32, size: u16) -> Result<(), failure::Error> {
    let output = std::fs::File::create(path)?;
    let mut encoder = image::gif::Encoder::new(output);

    for mut data in frames {
        let frame = image::gif::Frame::from_rgba_speed(size, size, &mut data, speed);
        encoder.encode(&frame)?;
    }

    Ok(())
}
```

I've checked the code and can't find any option to turn looping on.

**Comment by HeroicKatora** [comment]
The `image` crate tries to offer a unifying and stable interface. If you need specialized behaviour, it is better to use the `gif` crate directly. In particular it allows setting [extension data for repetitions](https://docs.rs/gif/0.10.3/gif/enum.ExtensionData.html#variant.Repetitions). This issue is still useful if one of You has a concrete idea how to design a common interface exposing the functionality here but otherwise I would encourage moving discussion to the `gif` crate.

**Comment by SystematicLoop** [comment]
I suppose I'll do that then.

The place where I figure you could insert functionality like that is when a frame is encoded or when a new frame is constructed. Maybe a field on a frame to say how many times to repeat and a special case for looping back. You could easily imagine that being a bit clunky though.

I'll go ahead and feed my data to the GIF crate as I did note it was capable of what I wanted. Thank you.
