### ISSUE TITLE
crash on trying to allocate too much memory in image::load_from_memory

### ISSUE THREAD

**Issue by alexanderkjall** [image-rs/image#1401]
This happens in the function image::load_from_memory

It's possible to construct image data in such a way that the library crashes due to it trying to allocate too much memory.

I'm not really sure if this is a bug that's fixable, but I would like to use the library to parse images that I get from the internet and crashes are not very nice.

## Expected

Maybe a Result with an error message. 

## Actual behaviour

What did happen:

```
$ RUST_BACKTRACE=1 ./target/debug/image-reproduce 
memory allocation of 98765234568 bytes failedAborted (core dumped)
```

## Reproduction steps

Can be reproduced with:

```
    let data = vec![0x50, 0x32, 0x32, 0x32, 0x32, 0x32, 0x32, 0x32, 0x0c, 0x32, 0x32, 0x32,
                    0x32, 0x32, 0x32, 0x0c, 0x32, 0x32, 0x32, 0x32, 0x32, 0x0c, 0x32, 0x4d,
                    0x4d, 0x4d, 0x35, 0x00, 0x00];

    let _ = image::load_from_memory(&data);
```

**Comment by fseegraeber** [comment]
This is trying to allocate roughly 222.222 x 222.222 `u16` wich is roughly 98GB. We should be able to handle this gracefully once [try_reserve](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.try_reserve) is stable.

**Comment by 5225225** [comment]
I don't think `try_reserve` is good enough here.

For example, I have 16GB of RAM, and usually have about 7GB in use, but the following program is OOM killed, it does *not* hit the `.unwrap()` on the `try_reserve`.

```rust
#![feature(try_reserve)]

const KB: usize = 1024;
const MB: usize = 1024 * KB;
const GB: usize = 1024 * MB;

fn main() {
    let mut x = Vec::<u8>::new();
    x.try_reserve(15*GB).unwrap();

    x.resize(x.capacity(), 42);
    println!("Hello, world!");
}
```

I assume it *does* work fine on systems without overcommit, but on Linux, it doesn't work.

A more reasonable approach IMO is to use limits, like we do elsewhere, and default to refusing to allocate more than, say, 64MB (bikeshed number as needed) by default. Those limits can be changed if you trust your input, but on a machine with that's not running close to being out of RAM, decoding an image with the default settings should never OOM the system.

**Comment by baumanj** [comment]
Another alternative (what [mp4parse](https://github.com/mozilla/mp4parse-rust) does) would be using https://github.com/vcombey/fallible_collections

**Comment by HeroicKatora** [comment]
Not fully. Fallible collections reduce the risk of outright crashing but don't address the DOS-potentially inherent in running without limits. When a program runs on systems with overcommit or even generally any system sharing memory space between competing tasks you can have an allocation succeed but reserve so much memory that by the time you utilize that memory the system as a whole runs into issues because the process is starving other tasks of that same resource. Or different, they just grind to a slow halt by the OS preserving stabiliy at the cost of runtime (moving everything to slow swap memory). In the worst case this leads to a meta stable system: Tasks start to fail and the actions needed to recover the system to a state without the decoder cost so much that they fail again, and again, and again. (Sounds like a theoretical concern but this _can_ happen in pratice. For example consider that decoding might have retry mechanism. Oops.)

What I'm saying: if it were possible to control the maximum resource usage up-front then some outer program can also pre-commit and reserve those resource, or at least judge if it's likely safe to try the action.

**Comment by fintelia** [comment]
This crash is now fixed
