### ISSUE TITLE
Allow atomics-based pixels instead of only raw primitives

### ISSUE THREAD

**Issue by RReverser** [image-rs/image#1431]
I would like to be able to use atomic types - either from `std::sync::atomic::*` or via the `atomic` crate - in order to safely draw onto the same image from multiple threads.

My specific use case for this functionality is plotting coordinates given by coordinates in a large list (star database) onto the image buffer.

This is more generally applicable to any use-cases that want to do `put_pixel` onto the same buffer from multiple threads as efficiently as possible (without locking the whole buffer, or creating separate images).

FWIW I realise it doesn't work for _every_ usecase, where overlaps might happen and need to be handled in some specific way / order, but in many cases it doesn't matter or the data already guarantees that overlaps don't occur, and those could benefit from lock-free multithreaded drawing.

For now, my workaround looks like this:

```rust
let raw_data = unsafe {
    // Create a raw image buffer filled with black colour.
    // This is safe because AtomicU8 is guaranteed to have same
    // memory layout as u8, but faster because `vec![0_u8; ...]` uses `calloc`
    // while atomics would need to be initialized one by one.
    Box::from_raw(Box::into_raw(vec![0_u8; 3000 * 3000].into_boxed_slice()) as *mut [AtomicU8])
};

files
    .par_iter()
    .try_for_each(|path| -> anyhow::Result<()> {
        let f = File::open(path)?;
        let mmap = unsafe { Mmap::map(&f) }?;
        for obj in read_db(&mmap)? {
            let x = ...;
            let y = ...;
            let brightness = ...;
            raw_data[y * 3000 + x].store(brightness, Ordering::Relaxed);
        }
        Ok(())
    })?;

let raw_data = unsafe {
    // This is safe because AtomicU8 is guaranteed to have same
    // memory layout as u8, and we're done with atomics by now otherwise.
    Box::from_raw(Box::into_raw(raw_data) as *mut [u8])
};

image::save_buffer_with_format(
    "output.png",
    &raw_data,
    3000,
    3000,
    image::ColorType::L8,
    image::ImageFormat::Png,
)?;
```

However, as fun as it is to work with `unsafe` code and manual index calculations (like `y * 3000 + x` above), I would much prefer to be able to use `ImageBuffer` with atomic numbers directly.

I thought I'd be able to do just that with

```rust
image::ImageBuffer::from_pixel(6000, 6000, image::Luma([AtomicU8::new(0)]))
```

and at least use `get_pixel(x, y)[0].store(...)` instead of `put_pixel` - which doesn't require mutation, and could in theory work, but right now a lot of wrapper types including `Luma` require the data part to be a `Primitive`, which atomics don't implement.

Is adding atomics support something you'd be open to in the image crate?

**Comment by HeroicKatora** [comment]
So in theory an atomic-based buffer might also allow holding it as `Arc<[AtomicU8]>`, right? For reading into such buffers, I believe one could hack together a version that buffers some data a few pages at a time and transfers it via large `Relaxed` writes if that's okay, similar for writing, but a fallback option might always be necessary for some of the decoders. We can't propagate all target buffers downward to all the crates. In particular the `std::io::{Read, Write}` traits do not accept atomic buffers so any byte slice crossing this must have an intermediate buffer.

**Comment by HeroicKatora** [comment]
A quick update, based on feedback from some of the excellent people on Discord. The following two conversions are sound:

* `&mut [u8] -> &mut [AtomicU8] -> &[AtomicU8]`
* `&mut [AtomicU8] -> &mut [u8] -> &[u8]`
* but note that `&[AtomicU8] -> &[u8]` and `&[u8] -> &[AtomicU8]` are __not__

In other words, we can soundly read from and write to such buffers with all of the available interface, provided that we have a _unique_ reference to the buffer (resp. its container). It will be slightly weird to require `&mut self` in the signature for saving such an image, but that's all still better than having to reallocate or copy into a temporary. (It also won't conflict with these two options).

It sadly will not be easily possible to implement the `Pixel` trait for a pixel type with atomic channels. This is due to `channels` and `channels_mut` which requires it to be convertible from slices. In other words these would require implementing all of the `Primitive` requirements on the atomic types, which `NumCast` etc. and thus another newtype wrapper at least. This also blocks `GenericImage`, which is a pity.

We can still:
* use `FlatSamples` and `ImageBuffer` themselves. These structs don't inherently require their container types to dereference to a slice of primitive channels. It's probably feasible to add or relax some methods that would allow using the buffer type even when the trait impls of `GenericImageView` is not available. The same applies to `FlatSamples` from which we can always use the `SampleLayout` portion.
* relax the struct bounds in `flat::{View, ViewMut}` such that they can refer to atomic channels. They could then be augmented with converters to/from non-atomic channel types based on the above listed conversions, for interoperability. 
* augment the buffers with atomic channel types with methods to copy to/from the non-atomic buffers with the same layout, using the `Relaxed` ordering for minimal performance impact. This would also help with cases where you can not get unique access to the buffer. For the purpose of making a clone to an `ImageBuffer<Vec<_>>` would could at least provide an efficient implementation due to layout similiarity.
* add specialized read and write methods for the atomic-based buffer that could also use the cast approach, although it won't work reliably for `Arc<_>` as they both need unique references to the underlying buffer.

**Comment by RReverser** [comment]
> The following two conversions are sound:
> 
>     * `&mut [u8] -> &mut [AtomicU8] -> &[AtomicU8]`
> 
>     * `&mut [AtomicU8] -> &mut [u8] -> &[u8]`
> 
>     * but note that `&[AtomicU8] -> &[u8]` and `&[u8] -> &[AtomicU8]` are **not**

That is correct, and also the constraint I had to keep in mind and described in comments on `unsafe` blocks in my example.

> It sadly will not be easily possible to implement the `Pixel` trait for a pixel type with atomic channels. This is due to `channels` and `channels_mut` which requires it to be convertible from slices.

This shouldn't be an issue, as long as `Subpixel` in the returned `&[Subpixel]` is also an atomic. So, I'm not asking image crate to perform conversion in that case, just give me access to "raw" atomic pixel components.

> and thus another newtype wrapper at least

Yeah I started prototyping it via this approach, but then realised there's too many trait bounds at the moment and decided to raise a proper discussion issue instead.

---

Relaxing trait bounds would be already a good star, and then we can see what to do with exposing more APIs.

**Comment by RReverser** [comment]
> So in theory an atomic-based buffer might also allow holding it as `Arc<[AtomicU8]>`, right? For reading into such buffers, I believe one could hack together a version that buffers some data a few pages at a time and transfers it via large `Relaxed` writes if that's okay

Something like this is definitely possible, although in my usecase I didn't need `Arc` - reading/writing directly via shared reference was sufficient.

**Comment by fintelia** [comment]
Stepping back, generic functions which accept an ImageBuffer likely assume that the underlying pixel data doesn't change between accesses and allowing pixel components to be atomics would violate that. But it also seems that you aren't looking for any of the fancy algorithms on ImageBuffers and the functionality you do need (construction, put_pixel, casting as &[u8]) shouldn't take that much code to implement separately.
