### ISSUE TITLE
Grab image from screen

### ISSUE THREAD

**Issue by wormtql** [image-rs/image#1555]
in python, you can grab an image from screen using pilllow, for example:
```python
from PIL import ImageGrab

im = ImageGrab.grab((0, 0, 100, 100))
```

It would be very useful if this library can support direct image capturing from screen

**Comment by kaj** [comment]
Certainly usefull, but the implementation would have to be very different depending on desktop platform the user is on (`PIL.ImagGrab` only works on macOS and Windows, according to the error message I get when testing it).   So I believe such a feature should be implemented in a separate crate (or even a few crates for different platforms), rather than as a part of `image`.

**Comment by fintelia** [comment]
I agree that this is better suited to a standalone crate.
