### ISSUE TITLE
Why is the saved image size much greater than the original?

### ISSUE THREAD

**Issue by DmitrijVC** [image-rs/image#1625]
Hi, I am working on a project which involves sending images through TCP and I've noticed that after loading an image and then saving it without any manipulation it's size is much greater.

I've read the docs, but didn't find anything to solve my issue.

Here is the code I am using for testing:
```rust
let mut file = std::fs::File::open("input.jpg").unwrap();
let mut buffer = Vec::new();
file.read_to_end(&mut buffer);

let img = image::load_from_memory(&buffer).unwrap();
img.save("output.jpg");

let img_bytes = img.to_bytes();

println!("in:  {}\nout: {}", buffer.len(), img_bytes.len());
```
**And here are the results:**

- output 
```
in:  10174706
out: 218131305
```

- files 
<img src="https://image.prntscr.com/image/j-eevPqoSWGjh38M5mWU0w.png">

I've found out that in case of JPEG the "subsampling" is different, but I don't quite understand what it is and how can I change it.
Additionally in some cases with PNG the output was smaller in size and the differences were visible.

<img src="https://image.prntscr.com/image/rkVnzPePRoWWty0TWFqbJg.png">
<p align="center">
<img src="https://image.prntscr.com/image/g_2NnXyUQWaAVQmQK0EA3w.png" width=50%>
</p>

# 
Could someone please help and tell me what am I missing here, so I could save larger PNG and JPEG images in similar size to the original? 
Maybe there is something in the documentation that I haven't seen?
#

**Comment by johannesvollmer** [comment]
Subsampling is essentially a JPEG mechanism that stores some channels only at half the width and half the height. Activating it can save about half of the memory.


 Furthermore, writing a JPEG image is always done with a specific quality setting, regardless of whether you use this crate or any other software. The quality setting affects the file size of the JPEG image. As far as I know, the quality setting is not stored in the file though, so you will have to choose an arbitrary value - or leave it at the default. 

That being said, you could try to look for subsampling in the documentation. I don't know whether it is currently possible

**Comment by DmitrijVC** [comment]
Thanks, but I didn't find anything that might help in the documentation. 
I also tried changing some things in the crate, but it didn't go well. (guess that's because I don't know how certain image formats work)

**Comment by fintelia** [comment]
If you want to create small JPEG files you can adjust the quality with [JpegEncoder::new_with_quality](https://docs.rs/image/0.23.14/image/codecs/jpeg/struct.JpegEncoder.html#method.new_with_quality). Lower quality corresponds to smaller file sizes. However, since JPEG is a lossy format, it also means files with more [compression artifacts](https://en.wikipedia.org/wiki/Compression_artifact#Images).

The PNG format by contrast is lossless. The pixels of the output image always exactly match those from the input. The [PngEncoder::new_with_quality](https://docs.rs/image/0.23.14/image/codecs/png/struct.PngEncoder.html#method.new_with_quality) method lets you trade off increased compression time for smaller output files.

**Comment by DmitrijVC** [comment]
Thanks a lot @fintelia, that's exactly what I needed for my project. Idk how I didn't see that method
