### ISSUE TITLE
Anyway to make image corners rounded?

### ISSUE THREAD

**Issue by Wiper-R** [image-rs/image#1774]
Anyone knows a algorithm to make image corners rounded.. I can't find a right place to ask this question, maybe you guys can help.

**Comment by fintelia** [comment]
This is really intended for questions/issues specifically about the [`image`](https://crates.io/crates/image) crate, rather than generic image processing questions. But the high level idea of making rounded corners is to make the pixels near the image corners transparent, but leave the rest unchanged.
