### ISSUE TITLE
Implement compression control in other formats

### ISSUE THREAD

**Issue by ror6ax** [image-rs/image#1831]
I would like to be able to write JPGs with adjustable compression. #1208 enables this for PNG, other formats that support compression as a tweakable parameter should have the same API.

**Comment by anarchodin** [comment]
As far as I can tell, JPEG already _does_ have the same API for configurable compression: `JpegEncoder::new_with_quality`. What's more, because #718 was introduced with JPEG support already built-in, the JPEG quality setting can be used from portions of the high-level API.

I do think that the configurable compression stuff needs to be better documented. I only found any of this because I was looking through the source code to figure out how to make the AVIF encoder use halfway sane settings.

**Comment by ror6ax** [comment]
Thanks for sharing, that should be enough for me. +1 for better documentation. I'm just a rust beginner so there's skill issue at play but I found the API very confusing and underdocumented, even for pretty basic actions.
