### ISSUE TITLE
JPEG/PNG compression level / settings option (new Enum options ?)

### ISSUE THREAD

**Issue by gwpl** [image-rs/image#1842]
Using ver 0.24.5

How to set JPEG/PNG compression level /settings (and eventually other compression flags) , when saving?

I've found `save_with_format` but it seems to take only "Jpeg" as part of enum, without possibility to do `Jpeg(10)` or `Jpeg_with_compression(10)` or  `png_profile(png_with(out)_adam7_interlacing)`. something like that could back backwards compatible, and provide new comfortable of setting common flags?

example I tried to modify to make it work:

```
//use image::{ImageOutputFormat,ImageFormat,GenericImageView};
use image::{GenericImageView};

fn main() {
    // Use the open function to load an image from a Path.
    // `open` returns a `DynamicImage` on success.
    let img = image::open("test_input.png").unwrap();

    // The dimensions method returns the images width and height.
    println!("dimensions {:?}", img.dimensions());

    // The color method returns the image's `ColorType`.
    println!("{:?}", img.color());

    // Write the contents of this image to the Writer in PNG format.
    img.save("test_output_default.jpg").unwrap();

    // Now with JPEG quality 10%
    // TODO img.save_with_format("test_output_10.jpg", ImageOutputFormat::Jpeg(10));
}
```

**Comment by anarchodin** [comment]
This is related to #1831, but specifically asks about the high level API. As things stand, compression configuration is not generally available through that; you will need to instantiate each encoder with the given settings, aside from JPEG. For JPEG, you _can_ use `ImageOutputFormat` with `write_to` but _not_ `save_with_format`.

This inconsistency seems to be long-term, with `ImageOutputFormat` being introduced in #718 as a generic method to provide options to specific formats, but #1208 explicitly avoiding the use of that system - as adding data to the enum variant would be a breaking change.

**Comment by gwpl** [comment]
Thank you for response!

One think that I don't understand, maybe I can learn something:

>  as adding data to the enum variant would be a breaking change.

how adding another enum option would be breaking change?

If anum has options "A","B","C", then adding e.g. "D(foo)" shouldn't break things, because it's new extra enum option.Do I miss something? (apart form "breaking" aspect I may understand that maybe not optimal "design wise").

**Comment by anarchodin** [comment]
It's not adding another enum variant; for most of the formats in question it's changing existing enum variants - specifically, in #1208 the original proposal was to change `ImageOutputFormat::Png` into `ImageOutputFormat::Png(CompressionType, FilterType)`. A similar issue would arise with adding the (already available) encoder tweaks to AVIF.

Personally, I think this approach is wrong-headed, and the breaking changes should be made, especially because the `ImageOutputFormat` enum is of no value without providing the options, and if every encoder except JPEG needs to use a different approach (and that approach is also available for the JPEG encoder) why bother keeping it? Either the other configurable encoders should be available through the same high-level API, or this apparently promising but actually useless API needs to be dropped, because its presence is misleading. Both of those are breaking changes.

**Comment by fintelia** [comment]
I'd be on board with making a breaking change _once_ to get the API cleaned up, but repeated breaking changes every time we tweak the config options for a format would be unappealing.

Perhaps an API like this could work?

```rust
enum CompressionSpeed {
    /// Fastest compression but largest size
    Fast,
    /// Trade-off between size and speed
    Medium,
    /// Smallest size but potentially very slow to encode
    Small,
}

impl DynamicImage {
    fn write(writer: W, format: ImageFormat) {...}
    fn write_with_options(writer: W, format: ImageFormat, speed: CompressionSpeed, quality_percent: u8) {...}

    fn save(path: Path) {...} // already exists
    fn save_with_format(path: Path, format: ImageFormat) {...} // already exists
    fn save_with_format_and_options(path: Path, format: ImageFormat, speed: CompressionSpeed, quality_percent: u8)

    #[deprecated = "Use write() instead"]
    fn write_to(write: W, output_format: ImageOutputFormat) {...} // existing, but awkward to improve
}

**Comment by anarchodin** [comment]
I didn't mean to imply it was worth multiple breaking changes; more that it would be worth the work of collecting together what the existing options are and adding them together. Exposing simplified settings could certainly be helpful, although it's worth noting that the only fairly _common_ tuning knob is some notion of 'quality', which still differs drastically between codecs. That means you always have to take the format being used into consideration, which is probably why the `ImageOutputFormat` approach was taken.

Additionally, I think it's worth looking into how to make the detailed configuration more easily accessible. As things stand the only way to access the knobs for (at least) PNG, WebP and AVIF is by instantiating their respective encoders. That's not the stumbling block, from my perspective. The encoders share a trait, so it should be possible to treat them as interchangeable, right?

Except the `write_image` method takes ownership of the encoder, so you can't use a trait object to call it. This means that if you want to dispatch to _different_ image formats using encoders you create yourself, you end up essentially reimplementing `image::free_functions::write_buffer_impl` for the formats of concern. And, hey, look, `ImageOutputFormat` is being used there.

Honestly, I think that the public API is not the real issue here, but a manifestation of a problem in the _internal_ structure that needs to be looked at. _Surely_ there's some way to do this that does not involve a dozen match branches that look virtually identical. I think that once that one is figured out, a better public API becomes much easier to build.

**Comment by gwpl** [comment]
> CompressionSpeed

most compressors have more fine grained parameters, so overall direction "maybe yes", but probably with more specifics about parameters.

> It's not adding another enum variant; for most of the formats in question it's changing existing enum variants - specifically, in https://github.com/image-rs/image/pull/1208 the original proposal was to change ImageOutputFormat::Png into ImageOutputFormat::Png(CompressionType, FilterType)

Not necessarily.

One can leave e.g. `ImageOutputFormat::Jpeg` and add new `ImageOutputFormat::Jpeg_with_compression_quality(...)` or something like that. 
Adding new enum options should be backward compatible (i.e. **without breaking changes**) , wouldn't it ?

**Comment by fintelia** [comment]
We ended up adding [`write_with_encoder`](https://docs.rs/image/latest/image/enum.DynamicImage.html#method.write_with_encoder), so you can now do:

```rust
let encoder = JpegEncoder::new_with_quality(&mut writer, 95);
img.write_with_encoder(encoder)?;
```
