### ISSUE TITLE
Better handling of ExtendColorType images

### ISSUE THREAD

**Issue by fintelia** [image-rs/image#1849]
As mentioned in https://github.com/image-rs/image/pull/1846#issuecomment-1405380005, this library has very limited support for images color types that aren't in `ColorType`. I want to propose some backwards compatible API changes to fix that. Note that even after these changes, most of the effort to make these types useful would still live within the encoders/decoders

## Save ExtendedColorType images

```rust

trait ImageEncoder {
    /// Given image data with color type input_color_type, write an image with output_color_type.
    fn write_image_extended(
        self,
        width: u32,
        height: u32,
        data: &[u8],
        input_color_type: ExtendedColorType,
        output_color_type: ExtendedColorType,
    ) -> ImageResult<()> { ... }
}
```

```rust
trait Pixel {
    const EXTENDED_COLOR_TYPE: Option<ExtendedColorType> = None;
}
```

```rust
impl ImageBuffer {
    fn save<P: Pixel>(...) {}  // remove PixelWithColorType bound 
    fn save_with_format<P: Pixel>(...) {} // remove PixelWithColorType bound
    fn write_to<P: Pixel>(...) {} // remove PixelWithColorType bound
}
```

## Load ExtendedColorType images
```rust
trait ImageDecoder {
  /// Same as read_image, but the output buffer has the format specified by `original_color_type`.
  fn read_image_raw(self, buf: &mut [u8]) -> ImageResult<()> {
      // Backwards compatible implementation. Decoders that set
      // color_type != original_color_type should provide their own impl
      if self.color_type() == self.original_color_type() {
          self.read_image(buf)
      } else {
          Err(...)
      }
  }
}
```

```rust
impl io::Reader {
    /// Decodes directly to an ImageBuffer if the input is in the matching color type, 
    /// or returns an error otherwise.
    fn decode_typed<P: Pixel>(self) -> ImageResult<ImageBuffer<P>> { ... }
}

**Comment by HeroicKatora** [comment]
The problem we had with `PixelWithColorType` was that indicate the color type for channel-generic structs required specialization to implement properly. And that requirement was the driver behind putting them in a sealed trait. Additionally, since they are `const` accessible these become a *very* murky part of the public API. If anything, this increasese maintenance burden (in terms of compilation failure). I don't see any reason why this problem would not be encountered _again_ with the additional associated constant on `Pixel`.

Some information can not be encoded as an associated type constant every well. Enforcing `image::Rgb` to mean sRGB _already_, despite using strong types, proves rather fruitless already. I'd strongly vote against expanding the amount of information *only* available via type dispatch, i.e. `Read::decode_typed` in this case. If there's an underlying interface based on dynamic information below, and the type is used to remove an error path, sure. But not as the only method.

The way `trait Pixel {}` falls rather short here, unfortunately.

In any case, this was opened to address if `Luma<f32>` should get support in the core `ColorType`. This proposal doesn't argue either way. Since that type is basically the discriminant for `DynamicImage` I'd expect the argument to be centered around that.

In terms of the question, what can we do to improve interoperability between the core pixel color types and the IO types: the most obvious would be provide an abstraction around the layout/data coupling

        width: u32,
        height: u32,
        data: &[u8],
        input_color_type: ExtendedColorType,

If there were decently general (not generic) ways to deal with this as _one_ type and interface for fallible conversion it would be simpler to enable more types with more decoders. Similarly a mutable variant of this would also allow reading into an output buffer with non-core color type (i.e. not into `DynamicImage`).

**Comment by fintelia** [comment]
Agreed with everything!

It occurs to me that part of the divide is really that:
1.  `ColorType` is the discriminant for `DynamicImage`, while
2.  `PixelWithColorType`  exposes pixel type information so `ImageBuffer::save` works

Those two things have almost nothing to do with each other! It would take a major version bump, but we could change the type of `PixelWithColorType::COLOR_TYPE` and the encoders to use `ExtendedColorType`.
