### ISSUE TITLE
Can `image::codecs::png::PngDecoder` somehow preserve `png::Info::source_gamma`?

### ISSUE THREAD

**Issue by anforowicz** [image-rs/image#2001]
My goal is to replace `libpng` with a PNG decoder implemented in memory-safe Rust (e.g. no FFI, limited use of `unsafe`, etc.). One problem I've encountered is replicating gamma processing of the old code:

* The old code [asks `libpng`](https://source.chromium.org/chromium/chromium/src/+/main:ui/gfx/codec/png_codec.cc;l=197-207;drc=ccf1fbee1a326b812933b1524052a0a94af88026) to transform the output pixels using the gamma information from a PNG header.
* In theory Rust exposes gamma information in [`png::Info::gama_chunk`](https://docs.rs/png/latest/png/struct.Info.html#structfield.gama_chunk), but:

    - The gamma value is *not* exposed via `image::codecs::png::PngDecoder`
    - Even if the gamma value was exposed, I wasn't able to identify Rust crate that implements an equivalent of [`png_do_gamma`](https://github.com/glennrp/libpng/blob/f8e5fa92b0e37ab597616f554bee254157998227/pngrtran.c#L3944).  Maybe this part is a *separate* feature request for the `image` crate but for `imageproc`?

AFAICT the problem can be reproed with `pngsuite/basn2c08.png`.

**Comment by anforowicz** [comment]
Would it be reasonable to:

* Tweak `image::codecs::png::PngDecoder` to also provide `gamma(&self) -> f32` method?
* Tweak `image::ImageDecoder` trait to require the same method?  (or maybe provide a default one that returns 2.2?)

Are there other alternatives that we can discuss?

I guess my short-term workaround can be:

* Work directly against the `png` crate (rather than using the `image::ImageDecoder` abstraction
* Continue using `image` crate for `Luma<u8>` => `Rgba<u8>` and other such conversions
* Implement the gamma correction myself

**Comment by fintelia** [comment]
I'm not actually sure what formats other than PNG let you specify a single gamma value to use for the image, so I think it makes more sense to add a `PngDecoder::gamma_value` method but not add it to `ImageDecoder`.

One thing to note about PNG is the rule that there's kind of complicated rules about how you determine the transfer function:

> An sRGB or iCCP chunk, when present and recognized, overrides the gAMA chunk.
>
> It is recommended that the sRGB and iCCP chunks do not appear simultaneously in a PNG datastream.
>
> When the cICP chunk is present, decoders that recognize it SHALL ignore the following chunks: iCCP, gAMA, cHRM, sRGB

As far as providing helper functions to do gamma correction, I think the best short term approach would be adding them to the png crate. That way they could reasonably be scoped to only the operations relevant to PNGs. I'd say it is probably only worth handling gAMA and sRGB to start since ICC profiles and cICP looks significantly more complicated
