### ISSUE TITLE
How to prevent bit-information loss on compression

### ISSUE THREAD

**Issue by Kaesebrot84** [image-rs/image#2039]
I have written a [small library](https://github.com/Kaesebrot84/hips-lib) which performs basic (text to image) steganography. Text data is hidden by encoding it into the lsb values of RGB values.

This approach works well on png files.

1. Load an png image
2. Hide text in it
3. Write resulting data to a png file

I am having issues with compressed formats (jpg in my case) though. The data stored in the RGB values, [gets lost](https://github.com/Kaesebrot84/hips-lib/issues/6) as soon as I write to jpg files.

My approach to a possible solution is to use [JpegEncoder::new_with_quality](https://docs.rs/image/latest/image/codecs/jpeg/struct.JpegEncoder.html#method.new_with_quality), set the quality to 100, in order to prevent as much compression as possible. This is what I have so far:

```rust
let result_img = hide_secret_img("test_images/peppers.png", &secret, Some(password));
let img = result_img.unwrap();

let mut buf: Vec<u8> = Vec::new();
let encoder = JpegEncoder::new_with_quality(&mut buf, 100);
img.write_with_encoder(encoder).unwrap();

image::save_buffer("out.jpg", &buf, img.width(), img.height(), image::ColorType::Rgb8).unwrap(); // panic
```

I am getting a `panicked` with this one:

> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /.../image-0.24.7/./src/codecs/jpeg/encoder.rs:459:65

I thought this might be an issue with the `ColorType` but it still fails after trying all of them.

So I have the following questions:

1. Is there any chance that this approach will solve the issue of data loss in jpg files?
2. How do I solve my `panic` issue on `image::save_buffer`?

**Comment by fintelia** [comment]
JPEG is a lossy file format, so the exact pixel values will not be retained after compression. PNG also has compression, but the compression algorithm it uses is lossless so the exact pixel values will be recovered. There are ways hide data that will survive JPEG compression, but that's somewhat out of scope of this library (search for "JPEG steganography" if you want to learn more).

The panic issue is from mis-using the API. The `save_buffer` expect raw pixel values, not an encoded image. Since you previously encoded the image data, you can replace that line with:
```rust
std::fs::write("out.jpg", &buf).unwrap();
```
