### ISSUE TITLE
Question: Using SIMD in Image?

### ISSUE THREAD

**Issue by JulianKnodt** [image-rs/image#2077]
Currently, I'm attempting to optimize bilinear interpolation, and have noticed there's some opportunities for SIMD, but I was wondering whether it would be ok to use portable SIMD (`std::simd`) inside the library?

**Comment by fintelia** [comment]
Portable SIMD isn't available in stable Rust yet, so any use would have to be behind an unstable feature flag [as we did for the png crate](https://github.com/image-rs/image-png/pull/414). (And even once it stabilizes we'd still have to wait until it was present in our MSRV before enabling it by default.)

The other consideration is that manually using SIMD has to be "worth it". The Rust compiler is very good at auto-vectorization so that should always be attempted first. And even when that's not possible, there has to be an impactful enough performance difference to justify making the code more complex.

**Comment by JulianKnodt** [comment]
sounds good, for now I'll avoid using it, but I'll try to fix up the code so that it's more amenable to optimization.
Right now I'm running the code in a hot path and I've found it to be slow,
I've also chucked it into godbolt and it's about 300 lines of asm with `-O`, so I'll try to shrink it down

**Comment by Shnatsel** [comment]
@JulianKnodt note that `-O` on godbolt does not optimize as much as `cargo build --release` does. You need to pass `-Copt-level=3` to get the high optimization level that includes auto-vectorization.

I've been banging my head for two hours on why the compiler won't autovectorize something, and it turned out that I was using `-O` on godbolt. I hope I am not too late to spare you this fate!

**Comment by JulianKnodt** [comment]
ah I didn't realize that, but I've updated the interpolation code to be more efficient in the unoptimized case, which is probably still good in the vectorized case: https://github.com/image-rs/image/pull/2078
