### ISSUE TITLE
WEBP encoding with compression?

### ISSUE THREAD

**Issue by Directory** [image-rs/image#2186]
The docs for the [`WebPEncoder`](https://docs.rs/image/latest/image/codecs/webp/struct.WebPEncoder.html#method.new_lossless) type only has a `new_lossless` method. Is it possible to make an instance of the webp encoder that can take a compression value similarly to how `JpegEncoder::new_with_quality` does it? the `webp` crate can do it but that crate is outdated and no longer works with the `DynamicImage` type from `image 0.25`.

**Comment by fintelia** [comment]
What specifically are you trying to achieve? If you only want to make sure that your webp file will be compressed, then the `new_lossless` method will be fine because that applies lossless compression.

If you're hoping to use lossy compression, however, that is currently not supported. You can read more here: https://github.com/image-rs/image/issues/1984

**Comment by Directory** [comment]
as of `webp 0.2.7` it now internally also supports `image 0.25`
