### ISSUE TITLE
Animated WebP's cannot actually be loaded

### ISSUE THREAD

**Issue by SludgePhD** [image-rs/image#2263]
`WebPDecoder` fails to decode WebP animations.

## Expected

It should probably work?

## Actual behaviour

- One file (`piston.webp` from the zip archive below) that works fine in Firefox and Chromium results in `UnexpectedEof` ("failed to fill whole buffer")
- Files from the `image-webp` test suite fail with "Format error decoding WebP: No more frames: No more frames"
  - https://github.com/image-rs/image-webp/tree/768b16b70b5a1d1315dda29ccc3777761a9b5a31/tests/images/animated

## Reproduction steps

`WebPDecoder::new(BufReader::new(File::open(path)?))?.into_frames().collect_frames()?`

[piston.zip](https://github.com/user-attachments/files/15927745/piston.zip)

**Comment by porkbrain** [comment]
I believe this to be a regression introduced in `0.25`.

My [code using `0.24`](https://github.com/porkbrain/bevy-webp-anim/blob/main/README.md#example) plays the image fine (also tested using this repo's `tests/images/webp/extended_images/anim.webp`), albeit the [`has_animation`](https://docs.rs/image/0.24.9/image/codecs/webp/struct.WebPDecoder.html#method.has_animation) method returns `false`.

After [update to `0.25`](https://github.com/porkbrain/bevy-webp-anim/pull/1/files) (wrapping the bytes in `Cursor` instead of passing them as `&[u8]`) I cannot play my test webp nor the one I mentioned above. As mentioned in the issue description, `collect_frames` runs into
> Format error decoding WebP: No more frames

Although ironically, after the update, the `has_animation` method now returns correctly `true`.

**Comment by porkbrain** [comment]
[This commit](https://github.com/image-rs/image/commit/fe7f010a81ffbe63b5532e8b990c11fd85c37e4f) breaks the webp animation loader.

**Comment by porkbrain** [comment]
This issue is actually quite straightforward. The iterator now returns an error if there are no more frames instead of `None`.

```rust
decoder
            .into_frames()
            .take_while(|frame| frame.is_ok())
            .collect()
```

Collecting the frames manually this way works. I will send an MR with a suggested fix as I believe `NoMoreFrames` should be caught in the iterator and converted to `None`.
