### ISSUE TITLE
ImageReader::open and write_to performance issue

### ISSUE THREAD

**Issue by nricciardi** [image-rs/image#2271]
This is not pure bug (maybe). `ImageReader::open` and `image.write_to` spent a lot of time. In my Rust project (custom Markdown compiler) run 50% of the execution time despite there are only 20 images on more than 5000 line that must be parsed.

Maybe open both operations can be improved or there are inefficient algorithms behind.

**Comment by fintelia** [comment]
Make sure you are compiling in release mode / with optimizations. Beyond that, this issue really isn't actionable without a lot more detail

PR's for specific optimizations are of course welcome!

**Comment by nricciardi** [comment]
Which details are needed?

However, I compile my application in release mode (optimization 3).

I will try to inspect code...

**Comment by fintelia** [comment]
To start with it would help to know which image format(s) you're dealing with. But even that isn't much to go on. Many of our encoders/decoders are thousands of lines of code and have already had a significant amount of optimization. In some cases they are slow primarily just due to the complexity of the format

The most actionable things would probably be providing specific image files that decode much faster with other libraries or profiling data identifying particular slow sections that could be improved

**Comment by fintelia** [comment]
The PNG encoder is already heavily optimized. AVIF as well, but you'll want to enable the `nasm` feature for best performance

**Comment by nricciardi** [comment]
Thank you, but, then I don't know how `open` and `write_to` are so a time consuming tasks...

Anyway, how can I use AVIF and what is `nasm` feature?

**Comment by fintelia** [comment]
The functions are time consuming because they do a lot of work. Just because each step is efficient doesn't mean it still won't take a while to complete.

You can encode to AVIF the same way you're currently doing for PNG, just change the file extension or pass `ImageFormat::Avif` as applicable. The `nasm` feature enables the `asm` feature on rav1e which you can read about in [their readme](https://github.com/xiph/rav1e?tab=readme-ov-file#features-1)

**Comment by nricciardi** [comment]
Thank you, I will try!
