### ISSUE TITLE
[Suggestion] Support HSV color

### ISSUE THREAD

**Issue by inDream** [image-rs/image#575]
I've tried to add HSV color but as I am beginner of rust, I cannot deal with float inside trait.
Anyone can help for the color type setup?

**Comment by nwin** [comment]
Can you please be more specific? In general it currently quite challenging  to abstract over number types in rust.

**Comment by inDream** [comment]
@nwin  I've added `HSV(f64)` in `pub enum ColorType`.
I need to change `#[derive(Copy, PartialEq, Eq, Debug, Clone)]` to
`#[derive(Copy, PartialEq, PartialOrd, Debug, Clone)]`
For error: no method named `assert_receiver_is_total_eq` found for type `f64` in the current scope.

And for marco rule `fn color_type() -> ColorType`, it need to determine the color type and I don't know how to get the size for float.

**Comment by nwin** [comment]
That is not how `ColorType` is intended to be used, it doesn’t contain any data, just the bit depth, hence add `HSV(u8)` to the enum.

Further you do not need to determine any size, the macro does everything for you, see [line 211](https://github.com/PistonDevelopers/image/blob/d79d156e3527d6511ad6a925c34d66a725b2ef97/src/color.rs#L211) on how to define a new pixel type.

**Comment by inDream** [comment]
@nwin So I need to use integer to represent HSV? i.e. [0-360, 0-100, 0-100]?
But I think this will loss precision during conversion.

**Comment by nwin** [comment]
No, you do not have to use integers to implement a HSV pixel type. I think you are still on the wrong track. `ColorType` is just representing the color type + bit depth. I does not say anything about the type used for implementing the actual logic. See `ColorType::RGB` and `Rgb<T>`.

**Comment by inDream** [comment]
@nwin So I need to define `HsvImage` in `buffer.rs` as:
`pub type HsvImage = ImageBuffer<Hsv<u8>, Vec<f64>>;` ?
When I do that, I got error E0308 & E0271 for all imageops:
```
error[E0271]: type mismatch resolving `<std::vec::Vec<f64> as std::ops::Deref>::
Target == [u8]`
   --> src\image\./src\dynimage.rs:311:38
    |
311 |         dynamic_map!(*self, ref p => imageops::blur(p, sigma))
    |         -----------------------------^^^^^^^^^^^^^^-----------
    |         |                            |
    |         |                            expected f64, found u8
    |         in this macro invocation
    |
    = note: required because of the requirements on the impl of `image::GenericI
mage` for `buffer::ImageBuffer<color::Hsv<u8>, std::vec::Vec<f64>>`

error[E0308]: mismatched types
   --> src\image\./src\dynimage.rs:311:38
    |
311 |         dynamic_map!(*self, ref p => imageops::blur(p, sigma))
    |         -----------------------------^^^^^^^^^^^^^^^^^^^^^^^^-
    |         |                            |
    |         |                            expected f64, found u8
    |         in this macro invocation
```
Also, as methods in `dynimage.rs` return `Vec<u8>`, how can I fix them?

current code: https://github.com/inDream/image/commit/b208750f6f8123849f4bbc17f9bcc7bdb629a0f3

**Comment by nwin** [comment]
After thinking about it, it would be best if you touch neither DynamicImage or ColorType for now, because it would break a lot of the public api without giving much benefit. Nevertheless I think it would be a valuable contribution to add HSV as a pixel type.

1. You do not need to define `HsvImage`, the other types are just a shortcut for commonly used types and currently I do not see any precedence of `Hsv<f32>` over `Hsv<f64>` (I guess `f32` is just good enough for most applications).
2. The reason is fails is because you use a Vector of `f64` as data storage for a type which is base on `u8` which won’t work. So you would need a `Hsv<f64>`instead.
3. For that to work you need to write specialized implementations of the `FromColor` trait such that you can properly convert between integer values and floats (e.g. `impl FromColor<Rgba<u8>> for Hsv<f64>` and friends) because the generic implementations only work if the underlying sub-pixel type is the same.

**Comment by inDream** [comment]
1. I think `HsvImage` is needed for add `to_hsv()` method.
2. Could you specific I need to change which file?
3. It produce new error when I do that:
```
error[E0277]: the trait bound `color::Hsv<_>: color::FromColor<color::LumaA<T>>`
 is not satisfied
   --> src\image\./src\color.rs:135:13
    |
135 |         pix.from_color(self);
    |             ^^^^^^^^^^ trait `color::Hsv<_>: color::FromColor<color::LumaA
<T>>` not satisfied
...
222 | define_colors! {
    | - in this macro invocation
    |
    = help: the following implementations were found:
    = help:   <color::Hsv<f32> as color::FromColor<color::Rgb<u8>>>
    = help:   <color::Hsv<f32> as color::FromColor<color::Rgba<u8>>>
    = help:   <color::Hsv<f32> as color::FromColor<color::LumaA<u8>>>
    = help:   <color::Hsv<f32> as color::FromColor<color::Luma<u8>>>

error[E0308]: mismatched types
   --> src\image\./src\color.rs:124:9
    |
124 |         pix
    |         ^^^ expected type parameter, found u8
...
222 | define_colors! {
    | - in this macro invocation
    |
    = note: expected type `color::Rgb<T>`
    = note:    found type `color::Rgb<u8>`
```

So currently it's difficult to support color type other than `u8`?

This is a related thread: https://www.reddit.com/r/rust/comments/2rez8d/
Updated code for ref: https://github.com/inDream/image/commit/22dbe228e307716e39695a87c6a480c757f7e418

**Comment by xd009642** [comment]
So I've had a brief look at implementing other colour spaces in Image because I'd like to use it and imageproc as the Rust alternative to my normal computer vision tools of C++ and OpenCV. OpenCV lets you represent HSV as any of the primitives supported so `float`, `u8`, `u16`, `u32` etc. So I set about implementing it like any of the other colour types.

However, you do then fall into the issue of #142 where `T::max_value()` isn't clamped to `1.0f` for `f32` or `f64`. 

On a side note, looking at all the possible colour spaces I wonder if an enum is the best approach just based on the number of possible formats. Although if anyone wants a format they can always add it as a PR. Just depends how open you are to all the different variants that may get submitted i.e. HSV, HSL, HSI, CIELAB, CIEXYZ, CIELUV?

**Comment by quietlychris** [comment]
Just to chime in, I would also be interested in an approach that would allow for additional pixel types to be added. As @xd009642 mentioned, color spaces like HSV and HSL are consistently used in computer vision tools, and would represent some of the fundamental building blocks to help build out certain feature detection algorithms in crates like `imageproc`, without needing to use OpenCV bindings.

An enum might work, but even an implementation of one or two of them the long way would be a help.
