### ISSUE TITLE
Better error for put_pixel when out of bounds

### ISSUE THREAD

**Issue by OmarShehata** [image-rs/image#601]
If you try to use [put_pixel](http://www.piston.rs/image/image/struct.ImageBuffer.html#method.put_pixel) with something that's out of bounds, it will panic with the following cryptic error:

```
thread 'main' panicked at 'index 961604 out of range for slice of length 960000', ../src/libcore\slice.rs:541
```

This confused me for a while because I wasn't using any vectors or slices in my program that I was aware of. It was not immediately clear because I was only off by one (trying to `put_pixel(400,400)` when my texture size was `600,400`).

I suggest something more descriptive like:

```
thread 'main' panicked at 'The point (400,400) is out of bounds for the given texture size of (600,400)'
```

Thoughts?

**Comment by johansen** [comment]
It surprises me that `put_pixel` and `get_pixel` panic on out-of-bounds rather than returning an error. Seems they should return a `Result` to indicate the success or failure of the operation. Un-checked variants could also be provided. This would parallel `Vec` where `get` returns a `Result` but indexing the vector panics on out-of-bounds.

**Comment by nwin** [comment]
I agree that `get_` might imply wrong expectations, but I would rather remove the methods than to make them "un-panic". I do not see any benefit for a Result::Err on an image indexing operation. This cannot fail unless you have a bug in your code.  The methods on Vec and HashMap are there for convenience since it is more commons for general collections to add  and remove elements. Images usually only get resized once.

**Comment by johansen** [comment]
Makes sense. More the array model than the vector model, I guess. Thanks for the explanation.

**Comment by martinlindhe** [comment]
The index out of range error comes from rust and is in fact a good indicator of what is going wrong, especially if you were to follow the stack trace.
Checked variants for get_pixel / put_pixel would be slower to use with little benefit.
As @nwin points out this cannot fail unless caller code has a bug.

I think this issue should be closed.

**Comment by fintelia** [comment]
Yeah, a backtrace should make this quite straightforward to debug. Also the panic message has been changed to almost exactly what the original post suggested: [panic!("Image index {:?} out of bounds {:?}", (x, y), (self.width, self.height)),](https://github.com/image-rs/image/blob/0961463caa9011d3e1a791691c91d84ad9c1c9ed/src/buffer.rs#L490). Closing.
