### ISSUE TITLE
"Constructors" for Rgb<T>?

### ISSUE THREAD

**Issue by LYP951018** [image-rs/image#696]
It seems that we could only construct a `Rgb<T>` object by 
```rust
Rgb<f32> { data: [1.0, 1.0, 1.0] }
```
This is truly leaky abstraction, and annoying. Also, access R, G, B by index is ... annoying, too.

**Comment by Veykril** [comment]
I was taking a look at this and noticed that the define_colors! macro in the color module actually defines a function with the same name as the struct with no documentation:  https://github.com/PistonDevelopers/image/blob/d000240fc263fde294236ace79e1873eaa7a20ac/src/color.rs#L65-L69
Nevertheless if the need for this is still there I'd love to make a constructor implementation for these things. I suppose they are meant to be of the signature(rgba as the example) `fn new(r: T, g: T:, b: T, a: T) -> Self`, what I'd like to ask is if it would be alright to change the define_colors! macro a bit to make it possible to implement them via the macro.

Also since OP said that indexing is a bit annoying, would an implementation of the single channels as function `fn r(&self) -> &T` / `fn rmut(&mut self) -> &mut T` also be something worth doing?

**Comment by mandeep** [comment]
I agree this is annoying. Also, in order to avoid having to index into each r, g, b component I'm using this `let [r, g, b] = self.im.get_pixel(i as u32, j as u32).data;`

**Comment by fintelia** [comment]
This interface has actually [changed on master since the last release](https://github.com/image-rs/image/pull/864). The constructors are gone, and `.data` is replaced by a tuple struct access: `.0`. That change also makes it possible to write your code slightly differently: `let Rgb([r,g,b]) = self.im.get_pixel(...);`

If you have thoughts on further tweaks we could make before releasing, this would be a good time to consider them.

**Comment by mandeep** [comment]
You can use `Rgb([r, g, b])` but then you have to dereference each component if you need to do something like cast to f64.  Tuple struct access would be a good compromise, however it doesn't seem to be available for me in this scenario:
```
let color = self.im.get_pixel(i as u32, j as u32);
let r = color.0;
```

I think my preferred way of access would be something like `let (r, g, b) = self.im.get_pixel(...)`

**Comment by HeroicKatora** [comment]
Not sure why you are under the impression that you would need to dereference the components. `get_pixel` returns an owned `Rgb<u8>` that is ordinarly destructured.

**Comment by HeroicKatora** [comment]
Ah, I see. Reworking everything to that nice destructuring is blocked by Rust 1.24.1. That may be the source of confusion, slice pattern syntax was still experimental back then. However, that will likely change pretty soon as well as this only compounds to the list of reasons to upgrade the minimum required compiler version.

**Comment by fintelia** [comment]
To clarify, this *does* work:
```rust
let [r, g, b] = self.im.get_pixel(i, j).0;
```

**Comment by HeroicKatora** [comment]
@fintelia No, same problem with Rust 1.24.1

```
error: slice pattern syntax is experimental (see issue #23121)
  --> examples/fractal.rs:38:17
   |
38 |             let [r, _, b] = pixel.0;
   |                 ^^^^^^^^^
```

**Comment by mandeep** [comment]
I see. I was using `let image::Rgb { data: [r, g, b] } = self.im.get_pixel(i as u32, j as u32);` because when using  `let image::Rgb([r, g, b]) = self.im.get_pixel(i as u32, j as u32);` I receive the error: `expected tuple struct/variant, found function image::Rgb` I'm sure I'm doing something wrong here, but not sure what.

When using `let [r, g, b] = self.im.get_pixel(i as u32, j as u32).0;` I receive the error: `no field 0 on type &image::Rgb<u8>`

**Comment by HeroicKatora** [comment]
@mandeep We're both talking about what is currently on `master` and what is going to be released next, not about what is released in `0.21.1`. You're probably utilizing the version from `crates.io`.

**Comment by mandeep** [comment]
@HeroicKatora gotcha, thanks!

**Comment by HeroicKatora** [comment]
You mean something like

```
impl<T: Copy> Rgb<T> {
    pub fn r(self) -> T {
        self.0[0]
    }
}
```

**Comment by mandeep** [comment]
Yep, or even providing a method that returns (r, g, b).

**Comment by fintelia** [comment]
I'm not sure I'm following why a tuple of (r,g,b) is preferable to an array. All the components are the same type, and with an array you can iterate over them if you want. Providing ways to access both would just clutter the interface

**Comment by mandeep** [comment]
@fintelia I agree that it doesn't matter what is returned, but I don't like how I have to use `.0` to do so.

**Comment by HeroicKatora** [comment]
We're not going to turn the type into a `[T; 3]` itself due to obvious trait troubles with reusing a type from the standard library. So how is `fn rgb(self) -> [T; 3]` preferrable over `rgb.0` to get to the representation?

**Comment by mandeep** [comment]
I think it's really just an aesthetic concern. I'm not sure `rgb.0` is as clear as something like `rgb.components()`. If I were someone not familiar with the code, I'd probably be wondering what `.0` actually is. Even `.data` is more explicit.

**Comment by mandeep** [comment]
I gave the master branch a try. This is what I mean by having to dereference:
```
        let image::Rgb([r, g, b]) = self.im.get_pixel(i as u32, j as u32);
        Vector3::new(*r as f64 / 255.0, *g as f64 / 255.0, *b as f64 / 255.0)
```

**Comment by HeroicKatora** [comment]
Can also be a single deref. And that's an unfortunate difference between `ImageBuffer` and `GenericImageView`, huh.

```
        let image::Rgb([r, g, b]) = *self.im.get_pixel(i as u32, j as u32);
        Vector3::new(r as f64 / 255.0, g as f64 / 255.0, b as f64 / 255.0)
```

**Comment by mandeep** [comment]
Yep.
