### ISSUE TITLE
Reading metadata without reading the entire file

### ISSUE THREAD

**Issue by elbaro** [image-rs/image#716]
I have large image files (>5MB). I want only the dimensions of them.
This code is very slow, taking >1s for each open.

```
let img = image::open(path).unwrap();
let (height, width) = img.dimensions();
```

How can I only retrieve the metadata?
I tried `image-utils` crate but it also uses `image` crate.

**Comment by elbaro** [comment]
Just found `immeta` crate works great for this. Please close this if lazy loading is not one of your goals.

**Comment by nwin** [comment]
Rust heavily relies on optimizations. Using `--release` when building your problem should drastically reduce the time it takes to open the image.

With regards to lazy loading, this is already supported just not for the convenience function `image::open`. The individual `ImageDecoder` implementation usually only read the meta data when calling `ImageDecoder::dimensions`. I agree that there should be a convenient way to do that.

**Comment by jramapuram** [comment]
Would love to see this feature. Trying to use `image` to crop a section of a 100k x 100k medical image, but this becomes intractable when using `image::open`.

**Comment by HeroicKatora** [comment]
@jramapuram It seems your use case is not restricted to metadata but rather as a streaming decoder. I'm not completely sure if the current [`Reader`] api already covers your use case since there is no generic equivalent to `open`, only format specific implementations.

Please open that as a new issue if it is not yet possible.

[`Reader`]: https://docs.rs/image/0.22.2/image/trait.ImageDecoder.html#associatedtype.Reader
