### ISSUE TITLE
Adhere to the Rust API guidelines

### ISSUE THREAD

**Issue by alteous** [image-rs/image#741]
This crate violates some of the [API guidelines](https://github.com/rust-lang-nursery/api-guidelines) recommended by the Rust library team. I understand the crate probably predates these guidelines; however, given the crate's prevalence, it is surprising that these guidelines are not adhered to.

Upon brief inspection, I noticed the following guidelines are were not followed:

#### Use of `Deref` trait ([C-SMART-PTR](https://rust-lang-nursery.github.io/api-guidelines/predictability.html#smart-pointers-do-not-add-inherent-methods-c-smart-ptr))
* `ImageBuffer` implements `Deref` but has its own methods such as `width` and `height`. This is forbidden by the guidelines.

#### Case convention ([C-CASE](https://rust-lang-nursery.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case))

There are many examples to choose from. Here are two:

* `ImageFormat::PNG` (opposed to `ImageFormat::Png`)
* `jpeg::JPEGDecoder` (opposed to `jpeg::JpegDecoder`)

The case convention is also inconsistent across the crate.

#### Getter convention ([C-GETTER](https://rust-lang-nursery.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter))

Again, there are many examples to choose from. Here are two:

* `ImageBuffer::get_pixel` (opposed to `ImageBuffer::pixel`)
* `GenericImage::get_pixel` (opposed to `GenericImage::pixel`)

#### Interoperability with `serde` ([C-SERDE](https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#data-structures-implement-serdes-serialize-deserialize-c-serde))

The crate makes no attempt to implement `serde` support.

Related issue: https://github.com/PistonDevelopers/image/issues/643

**Comment by alteous** [comment]
Although this is not part of the guidelines, I would like to add that names repeat themselves unnecessarily and this could be avoided by leveraging the module system. For example, instead of writing `image::ImageError::UnsupportedError`, one could write `image::Error::Unsupported`. Similarly, instead of writing `image::png::PngDecoder`, one could write `image::png::Decoder`.

**Comment by HeroicKatora** [comment]
This probably shouldn't be resolved as a single issue but split further when a decision is made to tackle specific problems. For example `C-Case` and `C-Getter` are probably easy, good first issues giving an overview over the complete library while not being complex. And serde support is quite obviously a big feature and needs planning.

**Comment by HeroicKatora** [comment]
I'd also like to add

**Generic Reader/Writer by value ([C-RW-VALUE](https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#generic-readerwriter-functions-take-r-read-and-w-write-by-value-c-rw-value))
As far as I have checked, this only concerns: 
  - `jpeg::BitWriter` and `jpeg::JPEGEncoder`

**Comment by nwin** [comment]
> however, given the crate's prevalence, it is surprising that these guidelines are not adhered to.

This is not surprising at all. Why should one use precious time fixing things that are not broken? Never chance a running system also applies to style. :)

It is also very important to understand that there are API guidelines which are resourceful because they greatly influence if and how you can use an API, these should be fixed. The others are just a matter of taste.

First category

 * `C-SERDE` I wouldn’t explicitly implement it. We really don’t have data structures that make sense to be serializable. In fact `image` is serializing library by itself. Nevertheless I’m sure there’ll be a way to automagically derive these kind of things in the future (see discussion about `Debug`, opt-in default traits etc.). So the problem will be probably be fixed by not doing anything.
 * `C-RW-VALUE` probably a good thing 👍

2nd

 * `C-SMART-PTR` makes sense. `AsRef` is probably more appropriate. 👍
 * `C-CASE` matter of taste guess, no urgent need to make everybody change their code. 👎 Could be fixed by a major version increment though.
 * `C-GETTER` is not followed by intention because it only makes sense if you don’t have a setter. If you have setters it makes the API too asymmetric. 👎

**Comment by GalAster** [comment]
I really need serde features, I'm using [bincode](https://github.com/servo/bincode) to transfer textures.

My current solution is to convert as bytes with `img.write_to(&mut buf, ImageOutputFormat::Png)` before transmission.

Then import bytes with `image::load_from_memory_with_format(buf, ImageFormat::Png)` after the transfer is complete.

In most cases, this is lossless, but I hope there is a better solution, and we can experiment with a feature flag that is turned off by default.

**Comment by afifurrohman-id** [comment]
> Every public module, trait, struct, enum, function, method, macro, and type definition should have an example that exercises the functionality.

https://rust-lang.github.io/api-guidelines/documentation.html#all-items-have-a-rustdoc-example-c-example

Instead of answer some common question over, and over again would be good to add example in docs.
why not?, this why i fun learn rust.

**Comment by fintelia** [comment]
> Instead of answer some common question over, and over again would be good to add example in docs. why not?, this why i fun learn rust.

If there's specific methods you think would benefit from an example, please open a PR!

(I'm going to close this issue because we've addressed some cases and broad issues like this aren't really actionable)
