### ISSUE TITLE
Can the HDR backend use rayon instead of scoped_threadpool?

### ISSUE THREAD

**Issue by icefoxen** [image-rs/image#772]
That would mean that between it and the `jpeg_rayon` feature this crate only bothers using one multithreading implementation.

Also `hdr_decode.rs` includes things like `let mut pool = Pool::new(8);`, which is kind of sub-ideal and using rayon would make it easier to be nicer.

**Comment by crazymykl** [comment]
It's at least not a drop-in replacement, since rayon's scope method runs on the pool, not the main thread.

**Comment by james7132** [comment]
I know this issue is old, but found this after checking why this crate has this dependency. It'd be ideal to provide a way to let users to handle the decoding themselves in their own multithreaded executors (i.e. rayon, tokio's blocking threads, etc.).

We're using this crate for Bevy's renderer, and one of the key things we're trying to avoid is thread contention and overhead from spawning too many. We're using our own thread pool, and would like for it to be the only one running over the lifetime of the app: spawning and joining 8 threads to decode one HDR image is generally undesirable on our end.

**Comment by fintelia** [comment]
Honestly in the short term it might make sense to just change the decoder to operate single threaded. Pulling in scoped_threadpool for a single rarely used format is a bit unfortunate. If it is too slow without multithreading (which I kind of doubt given that HDR isn't that complex a format), there's a bunch of other optimizations we could try.

Do you want to make a PR to get rid of the multithreading?
