### ISSUE TITLE
Resizing causes artifacts on some images

### ISSUE THREAD

**Issue by JulianWels** [image-rs/image#862]
I noticed that the resize algorithms (when used with an image that has slight banding) create very strange artifacts. How noticeable they are varies but they lead to way larger files.

![Banding](https://i.imgur.com/WX2zXa8.png)
For the tests above, I generated grey gradients in Illustrator and Photoshop, resized them with all available Filter-Types (except Nearest) and once through photoshop. Afterwards I extrapolated the levels so the results are clearer.
I also resized the images with OpenCV in C++ (INTER_AREA interpolation), which yielded similar results to what photoshop produced.

I don't know if this is a bug per se, but still wonder if this behaviour could be fixed.

**Comment by fintelia** [comment]
I don't think anyone would object to better resize algorithms. If I'm not mistaken, the current set produces good results when increasing image size, but not so great when reducing size. How reasonable do you think it would be to add INTER_AREA interpolation to the existing set?

**Comment by HeroicKatora** [comment]
The artifacts still looks somewhat suspicious to me, have a look at the full resolution version. There are almost grid-like darkened pixels across all filter types, that doesn't look correct?

**Comment by JulianWels** [comment]
@fintelia  Well, it's hard to work through [the code](https://github.com/opencv/opencv/blob/b39cd06249213220e802bb64260727711d9fc98c/modules/imgproc/src/resize.cpp#L3668) itself. Thankfully someone [made the effort](https://medium.com/@wenrudong/what-is-opencvs-inter-area-actually-doing-282a626a09b3) to decipher what INTER_AREA is actually doing. And as far as I have been able to understand this, it shouldn't be too hard to implement.

But I agree with @HeroicKatora that the results of the current filters seem incorrect.

**Comment by Shnatsel** [comment]
Could you provide the exact input images and code you've used? I have a hunch about what's going on but I need specific testcases to confirm it.

**Comment by JulianWels** [comment]
@Shnatsel [Here you go](https://github.com/JulianWels/image-artifacts). I tried to reproduce the image from above as close as possible. Since I deleted my reproduction repo a while back :(

As far as I can tell, the number of pixels by which the image is scaled down has a big influence on if and what kind of artifacts are created.

**Comment by Shnatsel** [comment]
Thank you! Since `image` crate contains some unsafe code, I've checked for memory errors with [Address Sanitizer](https://github.com/japaric/rust-san) and [libdiffuzz](https://github.com/Shnatsel/libdiffuzz). Fortunately, they've turned up nothing.

I'll run it through [miri](https://github.com/rust-lang/miri) just in case. I'm afraid I can't offer much assistance with fixing the code, though.

**Comment by okaneco** [comment]
This looks like it was fixed in #1408. I used `test-a.png` and an updated `main.rs` from the repo in https://github.com/image-rs/image/issues/862#issuecomment-468923361.

From left to right, the filters are Catmull, Gaussian, Lanczos3, and Triangle. The montages were created with imagemagick `convert +append`.

#### Commit before - 2721cd99d94eb2871f026f7396376dcf18708d4d

![pre](https://user-images.githubusercontent.com/47607823/107972755-4f316180-6f82-11eb-805b-5438644f58c4.png)

#### Commit after - 6d55953830d5e70fceda8abb442f92cbf10d9522

![post](https://user-images.githubusercontent.com/47607823/107972773-535d7f00-6f82-11eb-8bd6-992886c516b5.png)

---

As expected, the resulting file sizes are much smaller. 

| Before | Size | After | Size |
|---|---|---|---|
| pre-test-a-CatmullRom.png | 126884 | post-test-a-CatmullRom.png | 27054 |
| pre-test-a-Gaussian.png | 99363 | post-test-a-Gaussian.png | 27013 |
| pre-test-a-Lanczos3.png | 148180 | post-test-a-Lanczos3.png | 27047 |
| pre-test-a-Triangle.png | 49231 | post-test-a-Triangle.png | 27066 |

**Comment by HeroicKatora** [comment]
Closing this as fixed.
