### ISSUE TITLE
2 dimensional slices

### ISSUE THREAD

**Issue by arthmis** [image-rs/image#888]
Is it a possible to create 2d image views for the image buffer. For example if I wanted a 3x3 view of anywhere in the image. By a 2d slice, I mean something similar to the 1d slice you get for vectors but instead over a rectangular area of the image. I thought it might be useful when oerforming convolution over an image. 

 Is that what SubImage is for or does that create a new image?

**Comment by HeroicKatora** [comment]
That is exactly what [`GenericImage::sub_image`](https://docs.rs/image/0.21.0/image/trait.GenericImage.html#method.sub_image) is for, or use [`GenericImageView::view`](`https://docs.rs/image/0.21.0/image/trait.GenericImageView.html#method.view`) for a non-mutable alternative. Or, if you prefer calling the `SubImage` constructors directly, pass a `&_` or a `&mut _` as the first argument.

Tagging this as `documentation` because while the traits have doc, [`SubImage`](https://docs.rs/image/0.21.0/image/struct.SubImage.html) doesn't.

**Comment by lazypassion** [comment]
Can SubImage be used the way slice type is used? Or am I misunderstanding how SubImage compares to slice? I'm wondering if some of the methods slice implements would be possible for SubImage. (I don't know if these questions make sense.)

**Comment by fintelia** [comment]
Do you have particular methods you think are missing from SubImage? Looking over the documentation for slices, most don't seem to apply to images

**Comment by HeroicKatora** [comment]
It is also a major difference that `[T]` is a dynamically sized type while `SubImage` encapsulates a reference itself. The reason behind this is that it is simply not feasible in safe rust to have an encapsulation for a **non-contiguous** memory region whose allocation you don't control, note the pixels of a subimage are not contiguous in memory while contents of a slice are. This already makes `split_mut` etc. next to impossible to do safely, especially for the case where you take *any* `I: GenericImage`. In the special cases such as `ImageBuffer` and (in a release we really should do soon) `FlatSamples` this could be possible but still seems far from trivial.

**Comment by lazypassion** [comment]
Ah nevermind, I was under the impression that some methods like `chunks_mut()` would allow multithreading to be convenient but it seems it isn't possible to iterate over non-overlapping regions of arrays easily.
