### ISSUE TITLE
Please derive Clone, Debug, PartialEq and other traits on the ImageError

### ISSUE THREAD

**Issue by fschutt** [image-rs/image#896]
It's very annoying not being able to use a type in a unit test because the maintainer forgot to derive PartialEq, Clone and Debug - please derive all possible traits (Ord, Eq, Hash, Clone, etc.) on the `ImageError` type. There is no reason not to derive them, but it unnecessarily restricts what you can do with the error type, i.e. I can't derive Clone on an `enum MyError { Image(ImageError) }` because the image crate doesn't `#[derive(Clone)]` - which is IMO a very annoying mistake.

I can't fix it myself right now because there seem to be hiccups with this git repo (git clone succeds, but git checkout fails on Windows, due to weird things in the afl-tests, maybe someone rewrote git history in a weird way).

Thanks in advance.

**Comment by HeroicKatora** [comment]
I can't reproduce the checkout problems with a clean clone of `master`. Could it may be automatic line ending conversion?  Anyways, `ImageError` is not `Clone` since it has the variant `IoError(io::Error)`. So I can only advise you to create either a simple newtype wrapper around the `ImageError` or recreate the cloneable variants, both with proper `From<ImageError>` to allow ergonomic conversion.

Regarding the other possible derived traits, it is indeed not completely consistent and we'd be happy with a PR adding missed implementations!

**Comment by fschutt** [comment]
Yeah, well it's the usual problem - because `io::Error` derives absolutely nothing (a mistake in the standard library in my opinion), all wrapping errors can also not `#[derive(...)]` anything.

But please stop using Strings as errors or even worse, wrapping strings as `Io::Error(Box<dyn Error + 'static>)`. Right now there's a `UnsupportedImageFormat(ImageFormat)` error where the error could just wrap the error, but for some reason it gets turned into a `io::Error(ErrorKind::Other, format!("Unsupported format: {}", format))`:

https://github.com/image-rs/image/blob/cb485c0d41f28321900899a253756cabf2d26089/src/dynimage.rs#L850-L854

This is not how you do proper error handling! Just use `ImageError::UnsupportedError(format)`, no dynamic allocation necessary! Formatting the error should only be done in the `Display` function, not earlier and stop using `io::Error` as a wrapper for a `String`, it's not what `io::Error` was meant for.

**Comment by HeroicKatora** [comment]
> Yeah, well it's the usual problem - because io::Error derives absolutely nothing (a mistake in the standard library in my opinion), all wrapping errors can also not #[derive(...)] anything.

Not really. `io::Error` wraps arbitrary system errors. To not restrict the systems which Rust can support in the future, `io::Error` can not derive anything because otherwise adding new representations may be a semver change. It is not always appropriate to derive anything you can as available trait implementations of external crates (such as the `std`-lib) need to be consistent across semver compatible versions. So any derived trait also locks an enum into representations where each variant also has these traits, and a struct where each field has them. 

So, e.g. I don't think `Ord` would be appropriate for `ImageError` since while it may be orderable now, not each imaginable variant is orderable and more informative variant are also not orderable. While of course changing these variants is also a breaking change, just adding fields has at least a clear migration strategy while removing an available trait such as `Ord` causes major breakage with no direct alternative!

> But please stop using Strings as errors or even worse, wrapping strings as Io::Error(Box<dyn Error + 'static>)

Totally with you here, any such use should be replaced. I see the problem but I think the `try!` macro makes it clear that we are talking about old code :smile: Most newer usages of `io::Error` are due to loading and storing images inherently being `io` operators and use the error correctly. If you have the time to make these changes, they are very welcome.

**Comment by fschutt** [comment]
`Ord` is mostly useful for BTreeMaps, that's why I usually derive it even if it "doesn't make sense".

> To not restrict the systems which Rust can support in the future, io::Error can not derive anything because otherwise adding new representations may be a semver major version change.

Yeah, except that's not the case because (a) Rust doesn't support many operating systems and 99% of the market is taken up by the three main ones, Windows, Linux and Mac - and nearly zero new operating systems have been added in the last few years, it's not like a new OS is written every few months, (b) all operating systems use error codes for file system errors, which are comparable integers and therefore should have at least `PartialEq`, and `Clone` derived (so they can be used in unit tests) - and (c), on the one special OS where file system errors are not error codes, the standard library is likely to not even be used (bare metal or RTOS). It's optimizing for the potential 1% edge case, not the 99% of cases. But this is a problem of the standard library, not the image crate, so I won't complain about it here.

I'd rather like for the image crate to strip the IO handling, if possible, since `fs::read()` is now short enough to read images without writing a lot of code. I've also noticed that `IoError`, `FormatError` and `UnsupportedError` are highly misused as wrappers for strings, it would be better to create more distinct error types for them, i.e.: `UnsupportedError("color format unsupported")` should be split into a more proper type like `ImageError::ColorFormatUnsupported { max_bits: usize }` and so on - it gives a way better overview of what errors are actually possible.

**Comment by HeroicKatora** [comment]
> Ord is mostly useful for BTreeMaps, that's why I usually derive it even if it "doesn't make sense".

I feel that if you are using an `ImageError` or `io::Error` as *key* into a `BTree`, usually the design has bigger problems than the ~100 lines needed for a newtype-wrapper to enable this.

> I'd rather like for the image crate to strip the IO handling, if possible, since fs::read() is now short enough to read images without writing a lot of code.

While the sounds simple, it ignores some complexity when handling some image formats and use cases. The task of reading metadata is sped up greatly by only reading the relevant file sections and not letting it be read eagerly by the caller. The same is true for other methods that do not require the complete file, such as reading partial images or a single image from a sequence such as `.gif` and other such formats. Since the file type, and thus further parsing, depends on information being read *and* interpreted, the reading must be done within the parsing methods to enable this lazy file loading. So you don't get around having `io::Error` within at least these methods. 

The pragmatic choice was thus to only have one error type but that choice may be revised in the future with a design that can demonstrate gains from having it in-crate instead of a wrapper by the user.

**Comment by derekdreery** [comment]
I'd like to +1 implementation of common traits. If you feel there are downsides, you can always put them behind a feature (this is what the wasm-bindgen family of crates do). It's not always possible to anticipate how your types will be used, and, for me at least, it doesn't make sense to restrict them.

**Comment by Trolldemorted** [comment]
Could we at least get Clone, while you discuss about the others?

**Comment by fintelia** [comment]
Sadly, we can't implement `Clone` until `std::io::Error` does... which probably isn't happening anytime soon. It might be possible to work around it by wrapping the error in an `Arc`, but I haven't thought through the details
