### ISSUE TITLE
Issue and pull request templates

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/image#947]
I have no idea what I'm doing wrong in the setup here..

These work: https://github.com/HeroicKatora/oxide-auth

Maybe someone can help me out with ideas for this. Problem is that there is no good way to test them without merging to `master` as far as I know....

**Comment by HeroicKatora** [comment]
Okay, I think I figured something out by using my own fork... Turns out the frontmatter must start with **exactly** three `---`. Very intuitive.

**Comment by martinlindhe** [comment]
I think the filename sholuld be bug_report.md rather than bug-template.md

That, or any name can  be given thru the web interface.

Also looks like we could set up default templates for the image-rs organization to be reused across repos. Might be an option.

https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization

**Comment by HeroicKatora** [comment]
Yeah, but that requires setting up a `.github` repository for some reason. Could be worth it however, or we could move the `organization` repository under that name. I have a working setup now, and am going to write some templates. At least that provides the content and we can change their position later. The global files are also defaults, so no harm in having them duplicated here.

**Comment by HeroicKatora** [comment]
Update: templates work right now, the naming and global templates are not yet resolved. But we may want to close this issue and open the other portions as separate ones.
