### ISSUE TITLE
Convert ImageBuffer back to DynamicImage

### ISSUE THREAD

**Issue by cyberpunkbln** [image-rs/image#964]
Hello,

i have following problem.  I convert an ico into an png, overlay another png and want to write the overlayed png back to disk as an png.

```
let mut img_bg = image::open(&Path::new("gog_bg.png")).ok().expect("Opening image failed");
let mut img_png = image::open(&Path::new(&icoPath2.to_string())).ok().expect("Opening image failed");

let mut img_png2 = imageops::resize(&mut img_bg,100,100,FilterType::Lanczos3);
let mut img_png3 = image::load_from_memory (&img_png2).unwrap();

imageops::overlay(&mut img_bg, &img_png, 0, 0);
```

It's compile but after start the executable, this run-error appears:
`
thread 'main' panicked at 'calledResult::unwrap()on anErrvalue: UnsupportedError("Unsupported image format")', src\libcore\result.rs:997:5`

Seems like load_from_memory is not the right method for my needs., or i do something wrong and i must the ImageBuffer from imageops:resize operation convert?

When i handle the resize variable like the overlay variable rust says me:

```
imageops::overlay(&mut img_bg, &img_png2, 0, 0);
    |                                            ^^^^^^^^^ expected enum `image::DynamicImage`, found struct `image::ImageBuffer`
```

Wht make i wrong? And what are the difference between resize and overlay. Overlay takes an I and i don't now how the img_bg will be returned, its returned automaticly and resize gives a Imagebuffer back.

Thx for help.

**Comment by cyberpunkbln** [comment]
Hello,
an addition:  I don't must use imageops i can directly use DynamicImage for resize operation. Why overlay only functioned with imageops i have used imageops for resize. But the generally question is live, how can i use this ImageBuffer for DynamicImages? A litlle confusing why DynamicImages don't have overlay functions.

**Comment by HeroicKatora** [comment]
To answer these in order:

* The output of `resize` is already an in-memory image, you shouldn't try to load it. `image::load_from_memory` is for *decoding* an image given as e.g. `png` in a memory buffer.

* `imageops::overlay` currently requires both image arguments to be of the same type. (*Note*: that will no longer be required with the next release thanks to #880, expect it this weekend). In your code one has type `DynamicImage` while the other is `ImageBuffer` due to that being the output of `imageops::resize`. `DynamicImage` is a simple enum so you can manually change the type to match, with the line:

  > `imageops::overlay(&mut img_bg, &DynamicImage::ImageRgba8(img_png2), 0, 0)`

* `DynamicImage::resize` keeps the internal image representation while resizing with `imageops::resize` will always promote the image to pixel type `Rgba<u8>` into a new buffer. `overlay` on the other hand *modifies* the image provided in the first argument so there would be virtually no difference between providing such a function on `DynamicImage` itself, it would be just redundant.

**Comment by cyberpunkbln** [comment]
thx
