### ISSUE TITLE
How can I convert a image to a Writer?

### ISSUE THREAD

**Issue by darkskygit** [image-rs/image#967]
I wont to convert some image lossless and pipe to ffmpeg, but i can't find any api let me write the converted buffer to stdin(Writer) in this crate?

Now a plan is save to file and load it, but this will consume a lot of IO

**Comment by HeroicKatora** [comment]
I agree the situation is not optimal and there is no perfect generic solution. However most of the image encoder are generic over the `std::io::Write` instance to which they will output. Possible instantiations for the writer argument are thus: `Vec<u8>`, `&'_ mut [u8]`, `std::io::StdoutLock<'_>`, `std::process::ChildStdout`. The missing piece may be that only [`DynamicImage`](https://docs.rs/image/0.21.1/image/enum.DynamicImage.html#method.write_to) supports writing to arbitrary `Write` instances directly. For example writing an `ImageBuffer` as `png` to `hexdump`:

```
use std::process;
use image::{DynamicImage, ImageOutputFormat};

// .. insert fractal example here
let image: DynamicImage = DynamicImage::ImageRgb8(imgbuf);

let mut hexdump = process::Command::new("hexdump")
    .stdin(process::Stdio::piped())
    .spawn()
    .unwrap();

image.write_to(hexdump.stdin.as_mut().unwrap(), ImageOutputFormat::PNG)
    .unwrap()
```

One more pointer since you mention `ffmpeg`, a library. The [`flat`](https://docs.rs/image/0.21.1/image/flat/index.html) module is sort of the ffi interface for the `image` library. Its intended to provide C-style buffer view exactly for integrating with external libraries. I suppose you could utilize the [`ffmpeg_sys`](https://github.com/meh/rust-ffmpeg-sys) crate to create a temporary image mapping for ffmpeg with `av_frame_alloc`, `AVFrame` and `avpicture_fill`.

**Comment by darkskygit** [comment]
> I agree the situation is not optimal and there is no perfect generic solution. However most of the image encoder are generic over the `std::io::Write` instance to which they will output. Possible instantiations for the writer argument are thus: `Vec<u8>`, `&'_ mut [u8]`, `std::io::StdoutLock<'_>`, `std::process::ChildStdout`. The missing piece may be that only [`DynamicImage`](https://docs.rs/image/0.21.1/image/enum.DynamicImage.html#method.write_to) supports writing to arbitrary `Write` instances directly.
> 
> For example writing an `ImageBuffer` as `png` to `hexdump`:
> 
> ```
> use std::process;
> use image::{DynamicImage, ImageOutputFormat};
> 
> // .. insert fractal example here
> let image: DynamicImage = DynamicImage::ImageRgb8(imgbuf);
> 
> let mut hexdump = process::Command::new("hexdump")
>     .stdin(process::Stdio::piped())
>     .spawn()
>     .unwrap();
> 
> image.write_to(hexdump.stdin.as_mut().unwrap(), ImageOutputFormat::PNG)
>     .unwrap()
> ```
> 
> Writing other from other image buffer types requires instantiating the encoder manually as well as for most encoders manually specifying the `data: &[u8]` buffer, `width: usize`, `height: usize` and `color: ColorType`. This saves an indirection through `DynamicImage` but doesn't gain much else.
> 
> ```
> image::png::PNGEncoder::new(hexdump.stdin.unwrap())
>     .encode(&imgbuf, imgx, imgy, ColorType::RGB(8))
>     .unwrap();
> ```
> 
> One more pointer since you mention `ffmpeg`, a library. The [`flat`](https://docs.rs/image/0.21.1/image/flat/index.html) module is sort of the ffi interface for the `image` library. Its intended to provide C-style buffer view exactly for integrating with external libraries. I suppose you could utilize the [`ffmpeg_sys`](https://github.com/meh/rust-ffmpeg-sys) crate to create a temporary image mapping for ffmpeg with `av_frame_alloc`, `AVFrame` and `avpicture_fill`.

thinks!
image.write_to() work fine to me!

``` rust
fn pack_frames(files: &Vec<FrameInfo>, output: PathBuf) -> CompressResult<()> {
    let args = build_args(&output, get_frame_size(files));
    let mut child = Command::new(ARGS.get_ffmpeg())
        .args(&args)
        .stdin(Stdio::piped())
        .stdout(Stdio::inherit())
        .spawn()?;
    let mut stdin = child.stdin.as_mut().unwrap();
    for image in files.iter() {
        match open(&image.path) {
            Ok(image) => image.write_to(&mut stdin, ImageOutputFormat::PNG)?,
            Err(e) => err_handle.emit(CompressError::ImageParseError, e),
        }
    }
    child.wait()?;
    Ok(())
}
```
