### ISSUE TITLE
Is the master branch out of date?

### ISSUE THREAD

**Issue by aloucks** [image-rs/image#971]
There are quite a few commits on the version-0.21 branch that are not on master, including the version number update in Cargo.toml. Are the memory saftey fixes missing in master? 

Is this intended or an oversight?

https://github.com/image-rs/image/compare/version-0.21

**Comment by HeroicKatora** [comment]
Intended and not what is implied in the question. In fact `version-0.21` contains a strict subset of commits but rebased to exclude those that are breaking interface changes.

**Comment by HeroicKatora** [comment]
I'll add that the model for commits is planned to change with the next major version. Breaking ones are  likely going into a separate staging branch that is then merged with `master` on major version releases. Rebasing commits (rewriting into a new branch) was rather messy but necessary due to commits with breaking changes already having happened early. The new strategy for changes is intended to reduce the frequency of breaking releases to alleviate some pressure on upgrading.
