### ISSUE TITLE
Cannot save ImageBuffer created from jpg bytes

### ISSUE THREAD

**Issue by SKocur** [image-rs/image#976]
Hello, I encountered problem while saving ImageBuffer as a png image loaded from jpg file.

I should have seen generated (from these bytes) file with png extension. Currently it outputs nothing (until I force closing my program) and there is no error. 
I know that it will not correctly convert image from one format to another, [this program](https://github.com/SKocur/Image-Cipher/blob/master/src/rust/ImageBinaryConverter/src/main.rs#L62) is created in order to convert any file (even executable) read as `Vec<u8>` to png one. It works fine with any other format.

If I forgot any detail or I misunderstood some concept, I would like to apologize for it.

**Comment by theotherphil** [comment]
I had a look at your code using https://en.wikipedia.org/wiki/File:Sample_0.JPEG as an example image.

It looks like the problem is just that you're computing the image dimensions incorrectly and so allocating a giant buffer. In this case you're allocating a 192gb buffer to store the contents of a 2.6mb image.

The problem is the following calculation of size_y:

```let size_x = (bytes_to_pixels / 2.0) as u32;
    let size_y = (bytes_to_pixels - size_x as f32) as u32;
```

**Comment by SKocur** [comment]
Thank you @theotherphil for your suggestion. I fixed that error with
`let size_sqr = bytes_to_pixels.sqrt() as u32;`
Now it works for all formats. Truly speaking I haven't noticed this error during my tests with these kinds of files. Hmm, maybe I used too small data.
