### ISSUE TITLE
Unnecessary unsafety in HDR decoder

### ISSUE THREAD

**Issue by 64** [image-rs/image#980]
https://github.com/image-rs/image/blob/984e092827a6ec83fc7673047d5ca6cacf77b3ea/src/hdr/decoder.rs#L346

`Vec::set_len` leads to the creation of uninitialized memory which can be dropped if an error occurs during decoding. Additionally the other functions like `decode_component` have to be very careful to overwrite every single byte in the buffer lest uninitialized memory leak to the outside.

Is there any reason why `vec![0; n]` can't be used here? I doubt there would be a significant performance impact, if at all.

**Comment by HeroicKatora** [comment]
It's indeed not ok, maybe worse than you'd think since the type of `ret` is not a `Vec<u8>` but a generic `Vec<impl Send>`. @fintelia I believe the necessary changes were part of the original #887 but dropped for the `0.21` branch since they change the interface. Now would be a good time for a rebase of those since `0.22` is delayed either way.

**Comment by HeroicKatora** [comment]
Indeed: this PR removes it https://github.com/image-rs/image/pull/887/files#diff-9e9af5d18e72ec657d6b3c02cf35c490
