### ISSUE TITLE
implement imageops::replace for overlapping regions of an image

### ISSUE THREAD

**Issue by lovasoa** [image-rs/image#987]
Because of rust's borrowing limitations, it is currently not possible to use the various functions of this crate that  take two image references, one mutable and the other immutable with data that is coming from a single image. However, it is a completely reasonable operation to, for instance, replace a region of an image by another region of the same image, that may be overlapping.

This function could have the following form

```rust 
fn copy_to<I>(patch: SubImage<I>, destination: (u32,u32))
```

Having such a primitive would help me with my [seamcarving](https://github.com/lovasoa/seamcarving) implementation.

**Comment by HeroicKatora** [comment]
So like [`slice::copy_within`](https://doc.rust-lang.org/std/primitive.slice.html#method.copy_within) from which I would borrow the naming as well. It also provides a clear interface pattern of the form `copy_within(&mut self, from_region, to)` which would translate to

> `copy_within(&mut self, from: (u32, u32, u32, 32), to: (u32, u32))`

But there should problably be some proper `Rect` type for the first argument instead of that ad-hoc 4-tuple with unclear components. The problem with taking a subimage in the first argument is that this would be an active borrow of `self`and not possible.

**Comment by HeroicKatora** [comment]
Also, the simple implementation is just a loop in the correct order. `ImageBuffer` could provide a specialization to speed-up the process with the slice `copy_within` implementation but unfortunately we do not have actual specialization yet.

**Comment by lovasoa** [comment]
Why would it require specialization ? Couldn't it be done with a default trait method in `GenericImage`, and an implementation of this method in ImageBuffer ?

**Comment by HeroicKatora** [comment]
Sure, some better implementation than the default one is already an improvement for `ImageBuffer`.  I thought there might be additional speedup that could be gained from specializing for some `Pixel` types but you can probably subvert it and work on the raw `Subpixel` samples anyways which are required to be [`Copy`](https://docs.rs/image/0.21.2/image/trait.Primitive.html). So should be all good.

**Comment by HeroicKatora** [comment]
Closed in #1107.
